/* Format B — Vastrangam. Its own buyers, mills and marketplaces — the same engine as the
   neutral edition, carrying a real business so the neutrality can be tested. */
var CONFIG={
  id:'helpdesk_vastrangam', name:'Helpdesk & Live Chat', company:'Vastrangam', fy:'FY 2026-27',
  tagline:'Chat, email and phone become tickets tied to the order they are about — with the history already on the screen.',
  about:'A question arriving by any route becomes a ticket against the buyer who asked it, and usually against the order it is about. Whoever picks it up already has the whole history in front of them: what that buyer has bought, what came back from the marketplace, what is filed against them and what they asked last time. The first-reply clock is WORKED OUT from the messages rather than typed by anybody, so the number on the screen is the number that happened. A ticket cannot be closed without a single reply, and it cannot be attached to somebody else’s order.',
  docKinds:['Party','Order','Style or job','Person'],
  docTypes:['Supply agreement','Purchase order','Lab test report','Non-disclosure agreement','GST invoice copy','Delivery challan'],
  channels:['Live chat','Email','Phone','WhatsApp'],
  agents:['R. Nair','S. Kulkarni','A. Deshpande'],
  sla:{firstReplyMins:120,resolveMins:2880},
  sources:['Website enquiry','Referral','Exhibition','Cold outreach','Marketplace lead'],
  lossReasons:['Rate too high','Went to another supplier','Season already covered','Lost on payment terms'],
  wonType:'Wholesale', wonCity:'Surat',
  parties:[
    {id:'P1',name:'Rajmandir Wholesale (Surat)',type:'Wholesale',city:'Surat',email:'orders@rajmandir.example',since:'2025-06-14'},
    {id:'P2',name:'Chandni Chowk Boutique',type:'Boutique',city:'Delhi',email:'buying@chandnib.example',since:'2025-09-02'},
    {id:'P3',name:'Kanchi Silks House',type:'Wholesale',city:'Kanchipuram',email:'anita@kanchisilks.example',since:'2025-11-20'},
    {id:'P4',name:'Gulf Ethnic Trading FZE',type:'Export',city:'Dubai',email:'vikram@gulfethnic.example',since:'2025-04-08'},
    {id:'P5',name:'Highland Stores',type:'Wholesale',city:'Hyderabad',email:'sanjay@highland.example',since:'2025-02-15'},
    {id:'P6',name:'Aarti Deshmukh',type:'D2C',city:'Nagpur',email:'aarti.d@example.com',since:'2026-06-28'},
    {id:'P7',name:'Riverside Ethnic',type:'Boutique',city:'Ahmedabad',email:'meera@riverside.example',since:'2025-08-11'},
    {id:'P8',name:'Crestline Traders',type:'Wholesale',city:'Indore',email:'buying@crestline.example',since:'2026-07-12'}],
  leads:[
    {id:'L101',name:'Priya Menon',co:'Rajmandir Wholesale (Surat)',src:'Website enquiry',value:285000,stage:'new',status:'open',created:'2026-07-18',reason:'',party:''},
    {id:'L102',name:'Rahul Shetty',co:'Chandni Chowk Boutique',src:'Referral',value:420000,stage:'contacted',status:'open',created:'2026-07-02',reason:'',party:''},
    {id:'L103',name:'Anita Rao',co:'Kanchi Silks House',src:'Exhibition',value:675000,stage:'quoted',status:'open',created:'2026-06-14',reason:'',party:''},
    {id:'L104',name:'Vikram Nair',co:'Gulf Ethnic Trading FZE',src:'Cold outreach',value:890000,stage:'negotiation',status:'open',created:'2026-05-28',reason:'',party:''},
    {id:'L105',name:'Deepak Iyer',co:'Coastal Ethnic Wholesale',src:'Marketplace lead',value:240000,stage:'quoted',status:'open',created:'2026-06-30',reason:'',party:''},
    {id:'L106',name:'Sanjay Kulkarni',co:'Highland Stores',src:'Referral',value:510000,stage:'negotiation',status:'won',created:'2026-05-05',reason:'',party:'P5'},
    {id:'L107',name:'Meera Joshi',co:'Riverside Ethnic',src:'Website enquiry',value:335000,stage:'negotiation',status:'won',created:'2026-04-20',reason:'',party:'P7'},
    {id:'L108',name:'Arjun Pillai',co:'Crestline Traders',src:'Cold outreach',value:290000,stage:'quoted',status:'lost',created:'2026-04-08',reason:'Rate too high',party:''},
    {id:'L109',name:'Neha Bansal',co:'Orchid Ethnic',src:'Exhibition',value:175000,stage:'contacted',status:'lost',created:'2026-05-16',reason:'Went to another supplier',party:''},
    {id:'L110',name:'Farhan Qureshi',co:'Bluestone Mart',src:'Website enquiry',value:130000,stage:'new',status:'lost',created:'2026-06-02',reason:'Season already covered',party:''}],
  orders:[
    {id:'SO-1001',party:'P1',date:'2026-04-05',amount:148000,returned:0,channel:'Wholesale (Surat)'},
    {id:'SO-1002',party:'P1',date:'2026-05-12',amount:96500,returned:8500,channel:'Wholesale (Surat)'},
    {id:'SO-1003',party:'P1',date:'2026-06-08',amount:212000,returned:0,channel:'Wholesale (Surat)'},
    {id:'SO-1004',party:'P1',date:'2026-07-02',amount:134500,returned:12400,channel:'Exhibition / Exports'},
    {id:'SO-1005',party:'P1',date:'2026-07-20',amount:178000,returned:0,channel:'Wholesale (Surat)'},
    {id:'SO-1006',party:'P7',date:'2026-04-18',amount:84000,returned:0,channel:'Own Website'},
    {id:'SO-1007',party:'P7',date:'2026-05-22',amount:92000,returned:9200,channel:'Myntra'},
    {id:'SO-1008',party:'P7',date:'2026-06-19',amount:76500,returned:0,channel:'Own Website'},
    {id:'SO-1009',party:'P7',date:'2026-07-05',amount:118000,returned:6800,channel:'Flipkart'},
    {id:'SO-1010',party:'P2',date:'2026-04-11',amount:64000,returned:0,channel:'Wholesale (Surat)'},
    {id:'SO-1011',party:'P2',date:'2026-05-19',amount:58500,returned:5200,channel:'Wholesale (Surat)'},
    {id:'SO-1012',party:'P2',date:'2026-06-15',amount:71000,returned:0,channel:'Wholesale (Surat)'},
    {id:'SO-1013',party:'P3',date:'2026-04-22',amount:112000,returned:0,channel:'Wholesale (Surat)'},
    {id:'SO-1014',party:'P3',date:'2026-05-25',amount:98000,returned:33000,channel:'Myntra'},
    {id:'SO-1015',party:'P4',date:'2026-02-14',amount:88000,returned:0,channel:'Exhibition / Exports'},
    {id:'SO-1016',party:'P4',date:'2026-03-12',amount:45000,returned:0,channel:'Exhibition / Exports'},
    {id:'SO-1017',party:'P4',date:'2026-03-30',amount:132000,returned:11000,channel:'Exhibition / Exports'},
    {id:'SO-1018',party:'P5',date:'2025-10-05',amount:52000,returned:0,channel:'Wholesale (Surat)'},
    {id:'SO-1019',party:'P5',date:'2025-11-10',amount:61000,returned:6100,channel:'Wholesale (Surat)'},
    {id:'SO-1020',party:'P6',date:'2026-07-10',amount:39500,returned:0,channel:'Own Website'}],
  notes:[
    {id:'N1',party:'P1',date:'2026-07-21',kind:'Call',text:'Confirmed the July despatch arrived complete. Wants the same lead time before the festive cut.'},
    {id:'N2',party:'P1',date:'2026-06-09',kind:'Visit',text:'Met at their Surat office. Interested in the Banarasi line if we can hold the rate for six months.'},
    {id:'N3',party:'P4',date:'2026-04-02',kind:'Email',text:'Asked for a revised quote after the March shipment. No reply since — chase.'}],
  docs:[
    {id:'D-2001',title:'Supply agreement 2026-27',type:'Supply agreement',againstKind:'Party',against:'P1',issued:'2026-04-01',expires:'2027-03-31',status:'signed',signer:'Priya Menon',signedOn:'2026-04-03',code:'481920'},
    {id:'D-2002',title:'Rate contract — cotton line',type:'Supply agreement',againstKind:'Party',against:'P2',issued:'2026-05-10',expires:'2026-09-20',status:'signed',signer:'Rahul Shetty',signedOn:'2026-05-12',code:'770315'},
    {id:'D-2003',title:'Non-disclosure agreement',type:'Non-disclosure agreement',againstKind:'Party',against:'P4',issued:'2026-06-20',expires:'',status:'sent',signer:'Vikram Nair',signedOn:'',code:''},
    {id:'D-2004',title:'Lab test report — dye batch 4471',type:'Lab test report',againstKind:'Order',against:'SO-1013',issued:'2026-04-22',expires:'2026-08-15',status:'filed',signer:'',signedOn:'',code:''},
    {id:'D-2005',title:'Delivery challan SO-1005',type:'Delivery challan',againstKind:'Order',against:'SO-1005',issued:'2026-07-20',expires:'',status:'filed',signer:'',signedOn:'',code:''},
    {id:'D-2006',title:'Purchase order — festive cut',type:'Purchase order',againstKind:'Style or job',against:'VS-SAR-02',issued:'2026-07-05',expires:'',status:'draft',signer:'Anita Rao',signedOn:'',code:''},
    {id:'D-2007',title:'Supply agreement renewal',type:'Supply agreement',againstKind:'Party',against:'P3',issued:'2026-07-15',expires:'2026-08-31',status:'sent',signer:'Anita Rao',signedOn:'',code:''},
    {id:'D-2008',title:'GST invoice copy SO-1009',type:'GST invoice copy',againstKind:'Order',against:'SO-1009',issued:'2026-07-05',expires:'',status:'filed',signer:'',signedOn:'',code:''},
    {id:'D-2009',title:'Non-disclosure agreement — contractor',type:'Non-disclosure agreement',againstKind:'Person',against:'R. Nair',issued:'2026-03-02',expires:'2027-03-01',status:'signed',signer:'R. Nair',signedOn:'2026-03-04',code:'204877'},
    {id:'D-2010',title:'Rate contract — seasonal',type:'Supply agreement',againstKind:'Party',against:'P7',issued:'2026-06-01',expires:'',status:'declined',signer:'Meera Joshi',signedOn:'',code:''},
    {id:'D-2011',title:'Lab test report — annual',type:'Lab test report',againstKind:'Party',against:'P5',issued:'2025-08-05',expires:'2026-08-05',status:'signed',signer:'Sanjay Kulkarni',signedOn:'2025-08-07',code:'339104'},
    {id:'D-2012',title:'Delivery challan SO-1020',type:'Delivery challan',againstKind:'Order',against:'SO-1020',issued:'2026-07-10',expires:'',status:'filed',signer:'',signedOn:'',code:''}],
  tickets:[
    {id:'T-501',party:'P1',order:'SO-1004',channel:'Email',subject:'Two cartons short on the July delivery',priority:'High',agent:'R. Nair',opened:'2026-07-28T09:12',closed:'2026-07-28T15:40'},
    {id:'T-502',party:'P7',order:'SO-1009',channel:'Live chat',subject:'Wants to return part of the last order',priority:'Normal',agent:'S. Kulkarni',opened:'2026-07-29T11:05',closed:''},
    {id:'T-503',party:'P3',order:'SO-1014',channel:'Phone',subject:'Disputing the marketplace return credit',priority:'High',agent:'R. Nair',opened:'2026-07-26T16:20',closed:''},
    {id:'T-504',party:'P2',order:'',channel:'WhatsApp',subject:'Asking for the current rate list',priority:'Low',agent:'A. Deshpande',opened:'2026-07-30T10:02',closed:'2026-07-30T10:41'},
    {id:'T-505',party:'P6',order:'SO-1020',channel:'Live chat',subject:'Where is my order',priority:'Normal',agent:'A. Deshpande',opened:'2026-07-31T09:30',closed:''},
    {id:'T-506',party:'P4',order:'SO-1017',channel:'Email',subject:'Needs the test report for customs',priority:'High',agent:'S. Kulkarni',opened:'2026-07-24T08:15',closed:'2026-07-25T12:10'},
    {id:'T-507',party:'P5',order:'',channel:'Phone',subject:'Wants to reopen the account',priority:'Normal',agent:'R. Nair',opened:'2026-07-31T14:45',closed:''},
    {id:'T-508',party:'P1',order:'SO-1003',channel:'Email',subject:'Asking for a copy of the June invoice',priority:'Low',agent:'A. Deshpande',opened:'2026-07-22T13:00',closed:'2026-07-22T13:35'}],
  messages:[
    {id:'M1',ticket:'T-501',who:'customer',at:'2026-07-28T09:12',text:'We received the July delivery today and two cartons are missing against the challan.'},
    {id:'M2',ticket:'T-501',who:'us',at:'2026-07-28T10:04',text:'Thank you — checking the despatch record and the weight on the manifest now.'},
    {id:'M3',ticket:'T-501',who:'us',at:'2026-07-28T15:40',text:'Confirmed short at our end. A replacement despatch goes out tomorrow and the credit note is raised.'},
    {id:'M4',ticket:'T-502',who:'customer',at:'2026-07-29T11:05',text:'Some of the last lot is not moving. Can we send part of it back?'},
    {id:'M5',ticket:'T-502',who:'us',at:'2026-07-29T12:50',text:'Yes — within the agreed window. Send us the codes and quantities and we will raise the return.'},
    {id:'M6',ticket:'T-503',who:'customer',at:'2026-07-26T16:20',text:'The credit we received is short of what we returned.'},
    {id:'M7',ticket:'T-504',who:'customer',at:'2026-07-30T10:02',text:'Please send the current rate list.'},
    {id:'M8',ticket:'T-504',who:'us',at:'2026-07-30T10:41',text:'Sent, with the volume breaks marked.'},
    {id:'M9',ticket:'T-505',who:'customer',at:'2026-07-31T09:30',text:'Ordered three weeks ago and it has not arrived.'},
    {id:'M10',ticket:'T-506',who:'customer',at:'2026-07-24T08:15',text:'Customs is asking for the test report against the March shipment.'},
    {id:'M11',ticket:'T-506',who:'us',at:'2026-07-24T09:20',text:'Sending it now — it is filed against that order.'},
    {id:'M12',ticket:'T-506',who:'us',at:'2026-07-25T12:10',text:'Confirmed cleared. Closing this.'},
    {id:'M13',ticket:'T-507',who:'customer',at:'2026-07-31T14:45',text:'We stopped ordering last year. What would it take to start again?'},
    {id:'M14',ticket:'T-508',who:'customer',at:'2026-07-22T13:00',text:'Could we have a copy of the June invoice for our records?'},
    {id:'M15',ticket:'T-508',who:'us',at:'2026-07-22T13:35',text:'Attached — it was already filed against that order.'}],
  offers:{
    'Champion':'Give them first look at new lines and hold their rate. Ask for a referral — they will give one.',
    'Loyal':'Nudge the order size up. A small volume break costs less than finding a new buyer.',
    'Needs attention':'One phone call, not a discount. Find out what changed before assuming it is rate.',
    'At risk':'Call within the week. Ask what went wrong on the last order — usually something did.',
    'Sleeping':'One clear win-back offer with a deadline. If it does not land, stop spending on them.',
    'New':'Make the second order easy. The gap between one order and two is where most buyers are lost.'},
  segWhy:'Most businesses treat every buyer the same and then wonder why marketing money does nothing. These six groups are worked out from behaviour — how often somebody buys and how long ago — so the same effort goes where it will actually return something. A Champion needs holding on to; a Sleeping buyer needs one last try and then letting go.',
  wiring:[
    {f:'Open tickets',s:'This app',h:'Every ticket with no closing time on it'},
    {f:'Not answered yet',s:'This app',h:'Open, and nobody on our side has written a single message'},
    {f:'First reply time',s:'This app (the messages)',h:'The gap between the ticket opening and our first message on it — worked out, never typed'},
    {f:'Within the reply target',s:'This app + Platform (settings)',h:'First reply time against the target you set — 120 minutes as it ships'},
    {f:'Who the ticket is about',s:'CRM',h:'The party record, with everything already known about them'},
    {f:'Which order it is about',s:'E-commerce / OMS + Sales',h:'One of that party’s own orders — attaching anybody else’s is refused'},
    {f:'Documents to hand',s:'Documents',h:'Anything filed against that party or that order, ready to send'},
    {f:'By channel and by person',s:'This app',h:'Where the questions arrive and who is answering them'}],
  wiringIn:[
    {from:'CRM',what:'The party the ticket is about, and everything already on their record'},
    {from:'E-commerce / OMS',what:'Marketplace orders and returns a ticket can name'},
    {from:'Documents',what:'What is already filed against that party or order'},
    {from:'Platform',what:'The reply and resolution targets you set'},
    {from:'Logistics',what:'Where a delivery actually is, when that is the question'}]
};
