/* Format A — Unified ERP (any industry). Neutral names; the same engine runs a machine shop,
   a distributor, an exporter or a professional practice. Only this file changes. */
var CONFIG={
  id:'m02_erp', name:'Module 02 · CRM', company:'Acme Corp', fy:'FY 2026-27',
  tagline:'All three apps of Module 02 over one set of records — add, edit, delete, upload, and watch everything move.',
  about:'CRM & Customer 360, Documents & eSign and Helpdesk & Live Chat running on one shared set of records instead of three copies. Win a lead and the party appears on the customer list, with its documents and its tickets already hanging off it. File a document against an order and it shows up on that customer’s record. Answer a ticket and the first-reply clock moves everywhere at once. Type records in, or upload an Excel or CSV of them, or export the lot back out. This is the app to test with: anything you can do here, the three separate apps do on the same engine.',
  docKinds:['Party','Order','Project or case','Person'],
  docTypes:['Supply agreement','Purchase order','Quality certificate','Non-disclosure agreement','Invoice copy','Delivery note'],
  channels:['Live chat','Email','Phone','WhatsApp'],
  agents:['R. Nair','S. Kulkarni','A. Deshpande'],
  sla:{firstReplyMins:120,resolveMins:2880},
  sources:['Website enquiry','Referral','Trade show','Cold outreach','Marketplace lead'],
  lossReasons:['Price too high','Went to a competitor','Timing not right','Lost on payment terms'],
  wonType:'B2B', wonCity:'Mumbai',
  parties:[
    {id:'P1',name:'Northline Retail Pvt Ltd',type:'B2B',city:'Mumbai',email:'orders@northline.example',since:'2025-06-14'},
    {id:'P2',name:'Metro Distributors',type:'B2B',city:'Pune',email:'buying@metrodist.example',since:'2025-09-02'},
    {id:'P3',name:'Harbour Trading Co',type:'Wholesale',city:'Kochi',email:'anita@harbourtrading.example',since:'2025-11-20'},
    {id:'P4',name:'Sunrise Enterprises',type:'Export',city:'Dubai',email:'vikram@sunrise.example',since:'2025-04-08'},
    {id:'P5',name:'Highland Stores',type:'B2B',city:'Hyderabad',email:'sanjay@highland.example',since:'2025-02-15'},
    {id:'P6',name:'Aarti Deshmukh',type:'D2C',city:'Nagpur',email:'aarti.d@example.com',since:'2026-06-28'},
    {id:'P7',name:'Riverside Retail',type:'B2B',city:'Ahmedabad',email:'meera@riverside.example',since:'2025-08-11'},
    {id:'P8',name:'Crestline Traders',type:'Wholesale',city:'Indore',email:'buying@crestline.example',since:'2026-07-12'}],
  leads:[
    {id:'L101',name:'Priya Menon',co:'Northline Retail Pvt Ltd',src:'Website enquiry',value:285000,stage:'new',status:'open',created:'2026-07-18',reason:'',party:''},
    {id:'L102',name:'Rahul Shetty',co:'Metro Distributors',src:'Referral',value:420000,stage:'contacted',status:'open',created:'2026-07-02',reason:'',party:''},
    {id:'L103',name:'Anita Rao',co:'Harbour Trading Co',src:'Trade show',value:675000,stage:'quoted',status:'open',created:'2026-06-14',reason:'',party:''},
    {id:'L104',name:'Vikram Nair',co:'Sunrise Enterprises',src:'Cold outreach',value:890000,stage:'negotiation',status:'open',created:'2026-05-28',reason:'',party:''},
    {id:'L105',name:'Deepak Iyer',co:'Coastal Wholesale',src:'Marketplace lead',value:240000,stage:'quoted',status:'open',created:'2026-06-30',reason:'',party:''},
    {id:'L106',name:'Sanjay Kulkarni',co:'Highland Stores',src:'Referral',value:510000,stage:'negotiation',status:'won',created:'2026-05-05',reason:'',party:'P5'},
    {id:'L107',name:'Meera Joshi',co:'Riverside Retail',src:'Website enquiry',value:335000,stage:'negotiation',status:'won',created:'2026-04-20',reason:'',party:'P7'},
    {id:'L108',name:'Arjun Pillai',co:'Crestline Traders',src:'Cold outreach',value:290000,stage:'quoted',status:'lost',created:'2026-04-08',reason:'Price too high',party:''},
    {id:'L109',name:'Neha Bansal',co:'Orchid Retail',src:'Trade show',value:175000,stage:'contacted',status:'lost',created:'2026-05-16',reason:'Went to a competitor',party:''},
    {id:'L110',name:'Farhan Qureshi',co:'Bluestone Mart',src:'Website enquiry',value:130000,stage:'new',status:'lost',created:'2026-06-02',reason:'Timing not right',party:''}],
  orders:[
    {id:'SO-1001',party:'P1',date:'2026-04-05',amount:148000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1002',party:'P1',date:'2026-05-12',amount:96500,returned:8500,channel:'Wholesale / B2B'},
    {id:'SO-1003',party:'P1',date:'2026-06-08',amount:212000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1004',party:'P1',date:'2026-07-02',amount:134500,returned:12400,channel:'Retail Stores'},
    {id:'SO-1005',party:'P1',date:'2026-07-20',amount:178000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1006',party:'P7',date:'2026-04-18',amount:84000,returned:0,channel:'Retail Stores'},
    {id:'SO-1007',party:'P7',date:'2026-05-22',amount:92000,returned:9200,channel:'Online Marketplace'},
    {id:'SO-1008',party:'P7',date:'2026-06-19',amount:76500,returned:0,channel:'Retail Stores'},
    {id:'SO-1009',party:'P7',date:'2026-07-05',amount:118000,returned:6800,channel:'Retail Stores'},
    {id:'SO-1010',party:'P2',date:'2026-04-11',amount:64000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1011',party:'P2',date:'2026-05-19',amount:58500,returned:5200,channel:'Wholesale / B2B'},
    {id:'SO-1012',party:'P2',date:'2026-06-15',amount:71000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1013',party:'P3',date:'2026-04-22',amount:112000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1014',party:'P3',date:'2026-05-25',amount:98000,returned:33000,channel:'Online Marketplace'},
    {id:'SO-1015',party:'P4',date:'2026-02-14',amount:88000,returned:0,channel:'Export'},
    {id:'SO-1016',party:'P4',date:'2026-03-12',amount:45000,returned:0,channel:'Export'},
    {id:'SO-1017',party:'P4',date:'2026-03-30',amount:132000,returned:11000,channel:'Export'},
    {id:'SO-1018',party:'P5',date:'2025-10-05',amount:52000,returned:0,channel:'Retail Stores'},
    {id:'SO-1019',party:'P5',date:'2025-11-10',amount:61000,returned:6100,channel:'Retail Stores'},
    {id:'SO-1020',party:'P6',date:'2026-07-10',amount:39500,returned:0,channel:'Own Website'}],
  notes:[
    {id:'N1',party:'P1',date:'2026-07-21',kind:'Call',text:'Confirmed the July despatch arrived complete. Wants the same lead time next quarter.'},
    {id:'N2',party:'P1',date:'2026-06-09',kind:'Visit',text:'Met at their Mumbai office. Interested in the premium line if we can hold the price for six months.'},
    {id:'N3',party:'P4',date:'2026-04-02',kind:'Email',text:'Asked for a revised quote after the March shipment. No reply since — chase.'}],
  docs:[
    {id:'D-2001',title:'Supply agreement 2026-27',type:'Supply agreement',againstKind:'Party',against:'P1',issued:'2026-04-01',expires:'2027-03-31',status:'signed',signer:'Priya Menon',signedOn:'2026-04-03',code:'481920'},
    {id:'D-2002',title:'Rate contract — standard line',type:'Supply agreement',againstKind:'Party',against:'P2',issued:'2026-05-10',expires:'2026-09-20',status:'signed',signer:'Rahul Shetty',signedOn:'2026-05-12',code:'770315'},
    {id:'D-2003',title:'Non-disclosure agreement',type:'Non-disclosure agreement',againstKind:'Party',against:'P4',issued:'2026-06-20',expires:'',status:'sent',signer:'Vikram Nair',signedOn:'',code:''},
    {id:'D-2004',title:'Quality certificate — batch 4471',type:'Quality certificate',againstKind:'Order',against:'SO-1013',issued:'2026-04-22',expires:'2026-08-15',status:'filed',signer:'',signedOn:'',code:''},
    {id:'D-2005',title:'Delivery note SO-1005',type:'Delivery note',againstKind:'Order',against:'SO-1005',issued:'2026-07-20',expires:'',status:'filed',signer:'',signedOn:'',code:''},
    {id:'D-2006',title:'Purchase order — project fit-out',type:'Purchase order',againstKind:'Project or case',against:'PRJ-118',issued:'2026-07-05',expires:'',status:'draft',signer:'Anita Rao',signedOn:'',code:''},
    {id:'D-2007',title:'Supply agreement renewal',type:'Supply agreement',againstKind:'Party',against:'P3',issued:'2026-07-15',expires:'2026-08-31',status:'sent',signer:'Anita Rao',signedOn:'',code:''},
    {id:'D-2008',title:'Invoice copy SO-1009',type:'Invoice copy',againstKind:'Order',against:'SO-1009',issued:'2026-07-05',expires:'',status:'filed',signer:'',signedOn:'',code:''},
    {id:'D-2009',title:'Non-disclosure agreement — contractor',type:'Non-disclosure agreement',againstKind:'Person',against:'R. Nair',issued:'2026-03-02',expires:'2027-03-01',status:'signed',signer:'R. Nair',signedOn:'2026-03-04',code:'204877'},
    {id:'D-2010',title:'Rate contract — seasonal',type:'Supply agreement',againstKind:'Party',against:'P7',issued:'2026-06-01',expires:'',status:'declined',signer:'Meera Joshi',signedOn:'',code:''},
    {id:'D-2011',title:'Quality certificate — annual',type:'Quality certificate',againstKind:'Party',against:'P5',issued:'2025-08-05',expires:'2026-08-05',status:'signed',signer:'Sanjay Kulkarni',signedOn:'2025-08-07',code:'339104'},
    {id:'D-2012',title:'Delivery note SO-1020',type:'Delivery note',againstKind:'Order',against:'SO-1020',issued:'2026-07-10',expires:'',status:'filed',signer:'',signedOn:'',code:''}],
  tickets:[
    {id:'T-501',party:'P1',order:'SO-1004',channel:'Email',subject:'Two cartons short on the July delivery',priority:'High',agent:'R. Nair',opened:'2026-07-28T09:12',closed:'2026-07-28T15:40'},
    {id:'T-502',party:'P7',order:'SO-1009',channel:'Live chat',subject:'Wants to return part of the last order',priority:'Normal',agent:'S. Kulkarni',opened:'2026-07-29T11:05',closed:''},
    {id:'T-503',party:'P3',order:'SO-1014',channel:'Phone',subject:'Disputing the return credit',priority:'High',agent:'R. Nair',opened:'2026-07-26T16:20',closed:''},
    {id:'T-504',party:'P2',order:'',channel:'WhatsApp',subject:'Asking for the current rate list',priority:'Low',agent:'A. Deshpande',opened:'2026-07-30T10:02',closed:'2026-07-30T10:41'},
    {id:'T-505',party:'P6',order:'SO-1020',channel:'Live chat',subject:'Where is my order',priority:'Normal',agent:'A. Deshpande',opened:'2026-07-31T09:30',closed:''},
    {id:'T-506',party:'P4',order:'SO-1017',channel:'Email',subject:'Needs the certificate for customs',priority:'High',agent:'S. Kulkarni',opened:'2026-07-24T08:15',closed:'2026-07-25T12:10'},
    {id:'T-507',party:'P5',order:'',channel:'Phone',subject:'Wants to reopen the account',priority:'Normal',agent:'R. Nair',opened:'2026-07-31T14:45',closed:''},
    {id:'T-508',party:'P1',order:'SO-1003',channel:'Email',subject:'Asking for a copy of the June invoice',priority:'Low',agent:'A. Deshpande',opened:'2026-07-22T13:00',closed:'2026-07-22T13:35'}],
  messages:[
    {id:'M1',ticket:'T-501',who:'customer',at:'2026-07-28T09:12',text:'We received the July delivery today and two cartons are missing against the note.'},
    {id:'M2',ticket:'T-501',who:'us',at:'2026-07-28T10:04',text:'Thank you — checking the despatch record and the weight on the manifest now.'},
    {id:'M3',ticket:'T-501',who:'us',at:'2026-07-28T15:40',text:'Confirmed short at our end. A replacement despatch goes out tomorrow and the credit note is raised.'},
    {id:'M4',ticket:'T-502',who:'customer',at:'2026-07-29T11:05',text:'Some of the last lot is not moving. Can we send part of it back?'},
    {id:'M5',ticket:'T-502',who:'us',at:'2026-07-29T12:50',text:'Yes — within the agreed window. Send us the codes and quantities and we will raise the return.'},
    {id:'M6',ticket:'T-503',who:'customer',at:'2026-07-26T16:20',text:'The credit we received is short of what we returned.'},
    {id:'M7',ticket:'T-504',who:'customer',at:'2026-07-30T10:02',text:'Please send the current rate list.'},
    {id:'M8',ticket:'T-504',who:'us',at:'2026-07-30T10:41',text:'Sent, with the volume breaks marked.'},
    {id:'M9',ticket:'T-505',who:'customer',at:'2026-07-31T09:30',text:'Ordered three weeks ago and it has not arrived.'},
    {id:'M10',ticket:'T-506',who:'customer',at:'2026-07-24T08:15',text:'Customs is asking for the certificate against the March shipment.'},
    {id:'M11',ticket:'T-506',who:'us',at:'2026-07-24T09:20',text:'Sending it now — it is filed against that order.'},
    {id:'M12',ticket:'T-506',who:'us',at:'2026-07-25T12:10',text:'Confirmed cleared. Closing this.'},
    {id:'M13',ticket:'T-507',who:'customer',at:'2026-07-31T14:45',text:'We stopped ordering last year. What would it take to start again?'},
    {id:'M14',ticket:'T-508',who:'customer',at:'2026-07-22T13:00',text:'Could we have a copy of the June invoice for our records?'},
    {id:'M15',ticket:'T-508',who:'us',at:'2026-07-22T13:35',text:'Attached — it was already filed against that order.'}],
  offers:{
    'Champion':'Give them first look at new lines and hold their price. Ask for a referral — they will give one.',
    'Loyal':'Nudge the order size up. A small volume break costs less than finding a new customer.',
    'Needs attention':'One phone call, not a discount. Find out what changed before assuming it is price.',
    'At risk':'Call within the week. Ask what went wrong on the last order — usually something did.',
    'Sleeping':'One clear win-back offer with a deadline. If it does not land, stop spending on them.',
    'New':'Make the second order easy. The gap between one order and two is where most customers are lost.'},
  segWhy:'Most businesses treat every customer the same and then wonder why marketing money does nothing. These six groups are worked out from behaviour — how often somebody buys and how long ago — so the same effort goes where it will actually return something. A Champion needs holding on to; a Sleeping customer needs one last try and then letting go.',
  wiring:[
    {f:'Everything you type or upload',s:'This app',h:'Records are written once, in one place, and every screen reads them from there'},
    {f:'Pipeline and Customer 360',s:'CRM + Sales',h:'The CRM screens, on the records in this app'},
    {f:'Documents',s:'Documents',h:'The Documents & eSign screens, filing against the same party and order records'},
    {f:'Tickets',s:'Helpdesk',h:'The Helpdesk screens, about the same parties and the same orders'},
    {f:'One timeline per party',s:'CRM + Documents + Helpdesk + Sales',h:'Orders, documents, tickets, notes and the original lead, in one list, newest first'},
    {f:'Upload Excel or CSV',s:'This app',h:'Column headings are matched to fields, every row is checked, and anything rejected is shown with its reason'},
    {f:'Download Excel or CSV',s:'This app',h:'Every table written back out as a sheet, ready to hand to anybody'}],
  wiringIn:[
    {from:'Sales',what:'Orders and returns against the party record'},
    {from:'Marketing',what:'Which campaign a lead arrived from'},
    {from:'Accounting &amp; GST',what:'Whether they paid, and how late'},
    {from:'Projects & Collaboration',what:'Projects and cases a document can be filed against'},
    {from:'Platform',what:'The reply and resolution targets, and who is on the desk'}]
};
