/* Format B — Vastrangam (ethnic wear to the Gulf, UK, US and Australia). */
var CONFIG={
  id:'export_vastrangam', name:'Export', company:'Vastrangam', fy:'FY 2026-27', prefix:'VX-',
  ccy:'USD', fx:83.5,
  tagline:'Five papers, two tax routes, and the refund everybody forgets.',
  about:'For Vastrangam, export is the highest-margin channel there is — no marketplace commission and almost no returns — and it is a document problem, not a selling problem. This app tracks the five papers every shipment needs — commercial invoice, packing list, shipping bill, bill of lading, certificate of origin — and refuses to mark a shipment shipped until all five are in, because a missing certificate is what leaves a container at the port earning demurrage. It also handles the two lawful ways to deal with GST on an export: file an LUT bond and pay no IGST at all, or pay it and claim it back. On the second route the tax is your own working capital sitting with the government, so every unclaimed refund is listed with its age. Every rupee figure comes from one exchange rate held in one place.',
  ph:{buyer:'e.g. Al Fahim Textiles LLC (Dubai)'},
  countries:['United Arab Emirates','United Kingdom','United States','Singapore','Australia','Canada'],
  items:[
    {sku:'VS-KUR-01',name:'Cotton kurta set'},
    {sku:'VS-SAR-02',name:'Banarasi saree'},
    {sku:'VS-LEH-04',name:'Bridal lehenga'}],
  orders:[
    {id:'VX-901',buyer:'Al Fahim Textiles LLC (Dubai)',country:'United Arab Emirates',date:'2026-04-08',shipDate:'2026-04-20',
     sku:'VS-SAR-02',name:'Banarasi saree',qty:400,rate:42,route:'paid',status:'settled',
     docs:{ci:1,pl:1,sb:1,bl:1,coo:1},refunded:true},
    {id:'VX-902',buyer:'Saree House London Ltd',country:'United Kingdom',date:'2026-05-12',shipDate:'2026-05-22',
     sku:'VS-LEH-04',name:'Bridal lehenga',qty:120,rate:118,route:'paid',status:'settled',
     docs:{ci:1,pl:1,sb:1,bl:1,coo:1},refunded:false},
    {id:'VX-903',buyer:'Desi Threads Inc (New Jersey)',country:'United States',date:'2026-06-15',shipDate:'2026-06-24',
     sku:'VS-KUR-01',name:'Cotton kurta set',qty:900,rate:19,route:'lut',status:'landed',
     docs:{ci:1,pl:1,sb:1,bl:1,coo:1},refunded:false},
    {id:'VX-904',buyer:'Little India Traders (Singapore)',country:'Singapore',date:'2026-07-10',shipDate:'2026-07-19',
     sku:'VS-SAR-02',name:'Banarasi saree',qty:250,rate:44,route:'lut',status:'shipped',
     docs:{ci:1,pl:1,sb:1,bl:1,coo:1},refunded:false},
    {id:'VX-905',buyer:'Bollywood Boutique (Sydney)',country:'Australia',date:'2026-07-24',
     sku:'VS-LEH-04',name:'Bridal lehenga',qty:60,rate:122,route:'paid',status:'docs',
     docs:{ci:1,pl:1,sb:0,bl:0,coo:0},refunded:false},
    {id:'VX-906',buyer:'Punjabi Bazaar (Brampton)',country:'Canada',date:'2026-07-29',
     sku:'VS-KUR-01',name:'Cotton kurta set',qty:500,rate:20,route:'lut',status:'booked',
     docs:{},refunded:false}],
  routeNote:'If you export more than a few times a year, the LUT bond is almost always the right answer: it is one filing, and it keeps the tax money in your account instead of the government’s. The pay-and-claim route only makes sense while the bond is not yet in place.',
  taxNote:'On the pay-and-claim route you have already paid this tax. It is not a cost and it is not income — it is your own working capital held somewhere else until you ask for it back. Small exporters lose more money to unclaimed IGST refunds than to almost any other single leak, because nobody owns the list.',
  wiring:[
    {f:'FOB value in the buyer’s currency',s:'This app',h:'Quantity × the agreed rate per unit'},
    {f:'FOB value in ₹',s:'This app + one exchange rate',h:'Currency value × the single rate held on the Overview'},
    {f:'IGST',s:'This app + the tax route',h:'5% of the rupee value — but only on pay-and-claim shipments'},
    {f:'Saved by the LUT bond',s:'This app',h:'5% of everything on the bond route: tax that was never paid out'},
    {f:'Papers complete',s:'This app',h:'All five documents ticked. Anything less blocks the shipment from sailing'},
    {f:'Refund owed',s:'This app + Accounting &amp; GST',h:'IGST on shipments that have sailed and not yet been refunded'},
    {f:'Age of a claim',s:'This app',h:'Days since the shipment date. Past 60 days it is raised on the Overview'},
    {f:'Waiting to be paid',s:'Accounts Receivable',h:'Shipments that have sailed and not yet been settled'},
    {f:'Stock movement',s:'Inventory',h:'Leaves when the shipment sails, not when it is booked'},
    {f:'Ledger entry',s:'Accounting',h:'Export invoice posted at the rupee value on the shipping date'}],
  wiringIn:[
    {from:'Catalog',what:'The item and its export description'},
    {from:'Inventory',what:'Whether there is stock to ship'},
    {from:'Accounting',what:'The exchange rate policy and whether payment landed'},
    {from:'Accounting &amp; GST',what:'Whether the refund claim was accepted'},
    {from:'Logistics',what:'The carrier, the bill of lading and the sailing date'}]
};
