/* Format A — Unified ERP (any industry). Neutral names; drop-in for textile, medical, manufacturing, services. */
var CONFIG={
  id:'crm_erp', name:'CRM & Customer 360', company:'Acme Corp', fy:'FY 2026-27',
  tagline:'Lead to won, then the whole lifetime — every order, every return, what they are worth, what to offer next.',
  about:'One record per customer, carrying everything. On the way in it is a pipeline: a lead moves from New to Contacted to Quoted to Negotiation, and every stage carries a real probability, so the forecast is honest instead of hopeful. Once won, the same record becomes a Customer 360 — every order, every return, what the customer is actually worth after returns, how long since they last bought, and which of six behaviour groups they fall into. The groups are worked out by rule, not by anybody tagging people by hand, so they update themselves the moment somebody buys or goes quiet.',
  sources:['Website enquiry','Referral','Trade show','Cold outreach','Marketplace lead'],
  lossReasons:['Price too high','Went to a competitor','Timing not right','Lost on payment terms'],
  wonType:'B2B', wonCity:'Mumbai',
  ph:{name:'e.g. Priya Menon', coLabel:'Company / firm', co:'e.g. Northline Retail Pvt Ltd',
      note:'Called about the April order — asked for 45-day terms'},
  leads:[
    {id:'L101',name:'Priya Menon',co:'Northline Retail Pvt Ltd',src:'Website enquiry',value:285000,stage:'new',status:'open',created:'2026-07-18'},
    {id:'L102',name:'Rahul Shetty',co:'Metro Distributors',src:'Referral',value:420000,stage:'contacted',status:'open',created:'2026-07-02'},
    {id:'L103',name:'Anita Rao',co:'Harbour Trading Co',src:'Trade show',value:675000,stage:'quoted',status:'open',created:'2026-06-14'},
    {id:'L104',name:'Vikram Nair',co:'Sunrise Enterprises',src:'Cold outreach',value:890000,stage:'negotiation',status:'open',created:'2026-05-28'},
    {id:'L105',name:'Deepak Iyer',co:'Coastal Wholesale',src:'Marketplace lead',value:240000,stage:'quoted',status:'open',created:'2026-06-30'},
    {id:'L106',name:'Sanjay Kulkarni',co:'Highland Stores',src:'Referral',value:510000,stage:'negotiation',status:'won',created:'2026-05-05'},
    {id:'L107',name:'Meera Joshi',co:'Riverside Retail',src:'Website enquiry',value:335000,stage:'negotiation',status:'won',created:'2026-04-20'},
    {id:'L108',name:'Arjun Pillai',co:'Crestline Traders',src:'Cold outreach',value:290000,stage:'quoted',status:'lost',created:'2026-04-08',reason:'Price too high'},
    {id:'L109',name:'Neha Bansal',co:'Orchid Retail',src:'Trade show',value:175000,stage:'contacted',status:'lost',created:'2026-05-16',reason:'Went to a competitor'},
    {id:'L110',name:'Farhan Qureshi',co:'Bluestone Mart',src:'Website enquiry',value:130000,stage:'new',status:'lost',created:'2026-06-02',reason:'Timing not right'}],
  customers:[
    {id:'C1',name:'Northline Retail Pvt Ltd',type:'B2B',city:'Mumbai',since:'2025-06-14'},
    {id:'C2',name:'Metro Distributors',type:'B2B',city:'Pune',since:'2025-09-02'},
    {id:'C3',name:'Harbour Trading Co',type:'Wholesale',city:'Kochi',since:'2025-11-20'},
    {id:'C4',name:'Sunrise Enterprises',type:'Export',city:'Dubai',since:'2025-04-08'},
    {id:'C5',name:'Highland Stores',type:'B2B',city:'Hyderabad',since:'2025-02-15'},
    {id:'C6',name:'Aarti Deshmukh',type:'D2C',city:'Nagpur',since:'2026-06-28'},
    {id:'C7',name:'Riverside Retail',type:'B2B',city:'Ahmedabad',since:'2025-08-11'},
    {id:'C8',name:'Crestline Traders',type:'Wholesale',city:'Indore',since:'2026-07-12'}],
  orders:[
    {id:'SO-1001',cust:'C1',date:'2026-04-05',amount:148000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1002',cust:'C1',date:'2026-05-12',amount:96500,returned:8500,channel:'Wholesale / B2B'},
    {id:'SO-1003',cust:'C1',date:'2026-06-08',amount:212000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1004',cust:'C1',date:'2026-07-02',amount:134500,returned:12400,channel:'Retail Stores'},
    {id:'SO-1005',cust:'C1',date:'2026-07-20',amount:178000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1006',cust:'C7',date:'2026-04-18',amount:84000,returned:0,channel:'Retail Stores'},
    {id:'SO-1007',cust:'C7',date:'2026-05-22',amount:92000,returned:9200,channel:'Online Marketplace'},
    {id:'SO-1008',cust:'C7',date:'2026-06-19',amount:76500,returned:0,channel:'Retail Stores'},
    {id:'SO-1009',cust:'C7',date:'2026-07-05',amount:118000,returned:6800,channel:'Retail Stores'},
    {id:'SO-1010',cust:'C2',date:'2026-04-11',amount:64000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1011',cust:'C2',date:'2026-05-19',amount:58500,returned:5200,channel:'Wholesale / B2B'},
    {id:'SO-1012',cust:'C2',date:'2026-06-15',amount:71000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1013',cust:'C3',date:'2026-04-22',amount:112000,returned:0,channel:'Wholesale / B2B'},
    {id:'SO-1014',cust:'C3',date:'2026-05-25',amount:98000,returned:33000,channel:'Online Marketplace'},
    {id:'SO-1015',cust:'C4',date:'2026-02-14',amount:88000,returned:0,channel:'Export'},
    {id:'SO-1016',cust:'C4',date:'2026-03-12',amount:45000,returned:0,channel:'Export'},
    {id:'SO-1017',cust:'C4',date:'2026-03-30',amount:132000,returned:11000,channel:'Export'},
    {id:'SO-1018',cust:'C5',date:'2025-10-05',amount:52000,returned:0,channel:'Retail Stores'},
    {id:'SO-1019',cust:'C5',date:'2025-11-10',amount:61000,returned:6100,channel:'Retail Stores'},
    {id:'SO-1020',cust:'C6',date:'2026-07-10',amount:39500,returned:0,channel:'Own Website'}],
  notes:[
    {cust:'C1',date:'2026-07-21',kind:'Call',text:'Confirmed the July despatch arrived complete. Wants the same lead time next quarter.'},
    {cust:'C1',date:'2026-06-09',kind:'Visit',text:'Met at their Mumbai office. Interested in the premium line if we can hold the price for six months.'},
    {cust:'C4',date:'2026-04-02',kind:'Email',text:'Asked for a revised quote after the March shipment. No reply since — chase.'}],
  offers:{
    'Champion':'Give them first look at new lines and hold their price. Ask for a referral — they will give one.',
    'Loyal':'Nudge the order size up. A small volume break costs less than finding a new customer.',
    'Needs attention':'One phone call, not a discount. Find out what changed before assuming it is price.',
    'At risk':'Call within the week. Ask what went wrong on the last order — usually something did.',
    'Sleeping':'One clear win-back offer with a deadline. If it does not land, stop spending on them.',
    'New':'Make the second order easy. The gap between one order and two is where most customers are lost.'},
  segWhy:'Most businesses treat every customer the same and then wonder why marketing money does nothing. These six groups are worked out from behaviour — how often somebody buys and how long ago — so the same effort goes where it will actually return something. A Champion needs holding on to; a Sleeping customer needs one last try and then letting go.',
  wiring:[
    {f:'Open pipeline',s:'CRM itself (this app owns leads)',h:'Every deal still open, added up'},
    {f:'Likely to close',s:'CRM + stage odds',h:'Each deal × the probability of its stage: New 10%, Contacted 25%, Quoted 50%, Negotiation 75%'},
    {f:'Win rate',s:'CRM',h:'Deals won ÷ (deals won + deals lost)'},
    {f:'Customer worth',s:'Sales / Orders module',h:'Every order that customer placed, minus everything they sent back'},
    {f:'Returns and return %',s:'Sales returns',h:'Returned value ÷ gross ordered value, per customer'},
    {f:'Average order value',s:'Sales / Orders',h:'Customer worth ÷ number of orders they placed'},
    {f:'Last order date',s:'Sales / Orders',h:'The newest order on that customer — this is what drives the segment'},
    {f:'Segment',s:'All of the above',h:'One rule set on order count and days since last order — never tagged by hand'},
    {f:'What to offer next',s:'Segment',h:'One agreed action per group, so the same customer gets the same answer whoever opens the record'},
    {f:'Conversation log',s:'CRM itself',h:'Calls, visits and promises you record — the only thing here that is typed in'}],
  wiringIn:[
    {from:'Sales & Orders',what:'Every order, its channel, and anything returned'},
    {from:'Accounting',what:'Whether the customer actually paid, and how late'},
    {from:'Catalog',what:'What they bought, so the next offer makes sense'},
    {from:'Marketing / Automation',what:'Which campaign the lead arrived from'},
    {from:'CEO Dashboard',what:'Reads customer value and the at-risk count back out'}]
};
