/* Format B — Vastrangam (ethnic-wear D2C + marketplace, textile). Real buyers, boutiques, marketplace category managers, exhibition trade. */
var CONFIG={
  id:'crm_vastrangam', name:'CRM & Customer 360', company:'Vastrangam', fy:'FY 2026-27',
  tagline:'Boutique enquiry to confirmed buyer, then the whole lifetime — every order, every return, real worth.',
  about:'One record per buyer, carrying everything Vastrangam knows about them. On the way in it is a pipeline: a boutique enquiry or a marketplace category manager moves from New to Contacted to Quoted to Negotiation, and every stage carries a real probability so the forecast is honest instead of hopeful. Once won, the same record becomes a Customer 360 — every order, every return, and what that buyer is actually worth AFTER returns, which in this trade is a very different number from what they ordered. Marketplaces look enormous on gross and much smaller once the parcels come back; a quiet Jaipur boutique with 4% returns can be worth more than a big listing account. Six behaviour groups are worked out by rule, so a buyer moves group the moment they order or go quiet — nobody tags anybody by hand.',
  sources:['Boutique enquiry','Referral from a buyer','Exhibition / trade fair','Marketplace category manager','Instagram DM'],
  lossReasons:['Wanted a lower rate','Went to a Surat competitor','Delivery date did not suit','Could not agree credit terms'],
  wonType:'B2B', wonCity:'Surat',
  ph:{name:'e.g. Kavita Sharma', coLabel:'Boutique / firm / marketplace',
      co:'e.g. Anokhi Boutique (Jaipur)',
      note:'Called about the Banarasi lot — wants 30 pieces before Navratri'},
  leads:[
    {id:'L101',name:'Kavita Sharma',co:'Rangoli Boutique (Jaipur)',src:'Boutique enquiry',value:285000,stage:'new',status:'open',created:'2026-07-18'},
    {id:'L102',name:'Imran Sheikh',co:'Ajio (Reliance Retail)',src:'Marketplace category manager',value:420000,stage:'contacted',status:'open',created:'2026-07-02'},
    {id:'L103',name:'Sunita Agarwal',co:'Kanchan Sarees (Kolkata)',src:'Exhibition / trade fair',value:675000,stage:'quoted',status:'open',created:'2026-06-14'},
    {id:'L104',name:'Rakesh Doshi',co:'Vastra Bazaar (Surat wholesale)',src:'Referral from a buyer',value:890000,stage:'negotiation',status:'open',created:'2026-05-28'},
    {id:'L105',name:'Priyanka Nair',co:'Nykaa Fashion',src:'Marketplace category manager',value:240000,stage:'quoted',status:'open',created:'2026-06-30'},
    {id:'L106',name:'Deepa Menon',co:'Kalamandir Chain (Hyderabad)',src:'Referral from a buyer',value:510000,stage:'negotiation',status:'won',created:'2026-05-05'},
    {id:'L107',name:'Harshad Patel',co:'Anokhi Boutique (Jaipur)',src:'Exhibition / trade fair',value:335000,stage:'negotiation',status:'won',created:'2026-04-20'},
    {id:'L108',name:'Zoya Khan',co:'Meesho (seller desk)',src:'Marketplace category manager',value:290000,stage:'quoted',status:'lost',created:'2026-04-08',reason:'Wanted a lower rate'},
    {id:'L109',name:'Mahesh Rathi',co:'Ratan Textiles (Surat)',src:'Referral from a buyer',value:175000,stage:'contacted',status:'lost',created:'2026-05-16',reason:'Went to a Surat competitor'},
    {id:'L110',name:'Sneha Kulkarni',co:'Threads &amp; Weaves (Pune)',src:'Instagram DM',value:130000,stage:'new',status:'lost',created:'2026-06-02',reason:'Delivery date did not suit'}],
  customers:[
    {id:'C1',name:'Myntra (Myntra Designs Pvt Ltd)',type:'Marketplace',city:'Bengaluru',since:'2025-06-14'},
    {id:'C2',name:'Rajmandir Wholesale',type:'Wholesale',city:'Surat',since:'2025-09-02'},
    {id:'C3',name:'Anokhi Boutique',type:'B2B',city:'Jaipur',since:'2025-11-20'},
    {id:'C4',name:'Silk Route Exports',type:'Export',city:'Dubai',since:'2025-04-08'},
    {id:'C5',name:'Kalamandir Chain',type:'B2B',city:'Hyderabad',since:'2025-02-15'},
    {id:'C6',name:'Meera Deshpande',type:'D2C',city:'Pune',since:'2026-06-28'},
    {id:'C7',name:'Flipkart (Flipkart India)',type:'Marketplace',city:'Bengaluru',since:'2025-08-11'},
    {id:'C8',name:'Nykaa Fashion',type:'Marketplace',city:'Mumbai',since:'2026-07-12'}],
  orders:[
    {id:'VS-1001',cust:'C1',date:'2026-04-05',amount:148000,returned:0,channel:'Myntra'},
    {id:'VS-1002',cust:'C1',date:'2026-05-12',amount:96500,returned:8500,channel:'Myntra'},
    {id:'VS-1003',cust:'C1',date:'2026-06-08',amount:212000,returned:0,channel:'Myntra'},
    {id:'VS-1004',cust:'C1',date:'2026-07-02',amount:134500,returned:12400,channel:'Myntra'},
    {id:'VS-1005',cust:'C1',date:'2026-07-20',amount:178000,returned:0,channel:'Myntra'},
    {id:'VS-1006',cust:'C7',date:'2026-04-18',amount:84000,returned:0,channel:'Flipkart'},
    {id:'VS-1007',cust:'C7',date:'2026-05-22',amount:92000,returned:9200,channel:'Flipkart'},
    {id:'VS-1008',cust:'C7',date:'2026-06-19',amount:76500,returned:0,channel:'Flipkart'},
    {id:'VS-1009',cust:'C7',date:'2026-07-05',amount:118000,returned:6800,channel:'Flipkart'},
    {id:'VS-1010',cust:'C2',date:'2026-04-11',amount:64000,returned:0,channel:'Wholesale (Surat)'},
    {id:'VS-1011',cust:'C2',date:'2026-05-19',amount:58500,returned:5200,channel:'Wholesale (Surat)'},
    {id:'VS-1012',cust:'C2',date:'2026-06-15',amount:71000,returned:0,channel:'Wholesale (Surat)'},
    {id:'VS-1013',cust:'C3',date:'2026-04-22',amount:112000,returned:0,channel:'Wholesale (Surat)'},
    {id:'VS-1014',cust:'C3',date:'2026-05-25',amount:98000,returned:33000,channel:'Wholesale (Surat)'},
    {id:'VS-1015',cust:'C4',date:'2026-02-14',amount:88000,returned:0,channel:'Exhibition / Exports'},
    {id:'VS-1016',cust:'C4',date:'2026-03-12',amount:45000,returned:0,channel:'Exhibition / Exports'},
    {id:'VS-1017',cust:'C4',date:'2026-03-30',amount:132000,returned:11000,channel:'Exhibition / Exports'},
    {id:'VS-1018',cust:'C5',date:'2025-10-05',amount:52000,returned:0,channel:'Wholesale (Surat)'},
    {id:'VS-1019',cust:'C5',date:'2025-11-10',amount:61000,returned:6100,channel:'Wholesale (Surat)'},
    {id:'VS-1020',cust:'C6',date:'2026-07-10',amount:39500,returned:0,channel:'Own Website'}],
  notes:[
    {cust:'C1',date:'2026-07-21',kind:'Call',text:'July despatch received complete. Category manager wants 40 more Banarasi pieces before the festive window — hold the rate.'},
    {cust:'C1',date:'2026-06-09',kind:'Meeting',text:'Met at the Bengaluru office. Return rate is the only complaint — they blame the size chart, not the fabric. Fix the listing first.'},
    {cust:'C4',date:'2026-04-02',kind:'Email',text:'Asked for a revised quote after the March Dubai shipment. No reply since — chase before the exhibition season.'}],
  offers:{
    'Champion':'Give them first look at the new season and hold their rate. Ask for the festive indent early — they will commit.',
    'Loyal':'Push the indent size up. A small rate break on 40 pieces costs less than finding a new boutique.',
    'Needs attention':'One phone call, not a discount. In this trade it is usually a delivery date or a size-chart complaint, not price.',
    'At risk':'Call within the week. Ask what went wrong on the last lot — with fabric, something usually did.',
    'Sleeping':'One clear win-back offer tied to the festive window. If it does not land, stop spending on them.',
    'New':'Make the second order easy. The gap between one lot and two is where most boutiques are lost.'},
  segWhy:'In ethnic wear the temptation is to chase whoever places the biggest order and ignore everybody else. These six groups are worked out from behaviour instead — how often somebody indents and how long ago — so effort goes where it returns something. A Jaipur boutique that reorders every six weeks at 4% returns is often worth more than a marketplace account with a huge gross and 14% coming back.',
  wiring:[
    {f:'Open pipeline',s:'CRM itself (this app owns leads)',h:'Every boutique enquiry and marketplace conversation still open, added up'},
    {f:'Likely to close',s:'CRM + stage odds',h:'Each deal × the probability of its stage: New 10%, Contacted 25%, Quoted 50%, Negotiation 75%'},
    {f:'Win rate',s:'CRM',h:'Deals won ÷ (deals won + deals lost)'},
    {f:'Customer worth',s:'Channel Manager + Sales',h:'Every order that buyer placed, minus every parcel that came back — this is the number that matters, not gross'},
    {f:'Returns and return %',s:'Marketplace returns + sales returns',h:'Returned value ÷ gross ordered value, per buyer. Myntra and Flipkart are tracked separately because their behaviour differs'},
    {f:'Average order value',s:'Sales / Orders',h:'Buyer worth ÷ number of indents they placed'},
    {f:'Last order date',s:'Sales / Orders',h:'The newest indent on that buyer — this is what drives the segment'},
    {f:'Segment',s:'All of the above',h:'One rule set on indent count and days since the last one — never tagged by hand'},
    {f:'What to offer next',s:'Segment',h:'One agreed action per group, so the same buyer gets the same answer whoever opens the record'},
    {f:'Conversation log',s:'CRM itself',h:'Calls, exhibition meetings and promises you record — the only thing here that is typed in'}],
  wiringIn:[
    {from:'Channel Manager',what:'Myntra / Flipkart / website orders, returns and settlements'},
    {from:'Sales & Orders',what:'Every wholesale indent and export order, and anything returned'},
    {from:'Accounts / BUSY',what:'Whether the buyer actually paid, and how late'},
    {from:'Catalog',what:'Which designs and fabrics they bought, so the next offer makes sense'},
    {from:'CEO Dashboard',what:'Reads buyer value and the at-risk count back out'}]
};
