'use strict';
/* ONE ARCHIVE, BOTH EDITIONS — everything, for reading.
 *
 *   node brand/delivery/website/mkall.js   → MEDHAVA_AND_VASTRANGAM.zip
 *
 * The owner asked for a single zip of every document, in both forms. This is that. It is still
 * for READING: extracting the per-edition archive and testing the build prompt against it found
 * 18 of 22 paths absent and every command broken, and merging two such archives does not add a
 * schema to either. The README says so in the first line rather than the fifth.
 */
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = path.join(__dirname, '..', '..', '..');
const M = require('../manifest.js');
const OUT = path.join(ROOT, 'MEDHAVA_AND_VASTRANGAM.zip');

const files = [];
for (const ed of M.editions()) {
  M.forEdition(ed).forEach((d) => files.push(d.md, d.pdf));
  files.push(M.skillFor(ed).md, M.promptFor(ed).md);
  const shots = path.join(ROOT, ed === 'MEDHAVA'
    ? 'brand/delivery/website/MEDHAVA_BOS/shots' : 'brand/delivery/website/VASTRANGAM_BOS/shots');
  if (fs.existsSync(shots)) {
    fs.readdirSync(shots).filter((f) => f.endsWith('.png')).sort().forEach((f) =>
      files.push(path.posix.join(path.relative(ROOT, shots).split(path.sep).join('/'), f)));
  }
}

const missing = files.filter((f) => !fs.existsSync(path.join(ROOT, f)));
if (missing.length) {
  console.error(`mkall: ${missing.length} file(s) not built:\n  ` + missing.join('\n  '));
  process.exit(1);
}

const rows = M.editions().flatMap((ed) => [
  [`**${ed}**`, '', ''],
  ...M.forEdition(ed).map((d) => ['', `\`${path.basename(d.md, '.md')}\``,
    (d.start ? '**Start here.** ' : '') + d.what]),
  ['', `\`${path.basename(M.promptFor(ed).md)}\``, M.promptFor(ed).what],
  ['', `\`${path.basename(M.skillFor(ed).md)}\``, M.skillFor(ed).what],
]);

const readme = `# Medhava and Vastrangam — every document

## Read this first

**This archive cannot build anything, and is not meant to.** It carries documents and PDFs and no
source — no schema, no engine, no tests, no package file. That is checked, not assumed: extracting
the per-edition archive and testing the build prompt against it found **18 of its 22 paths absent
and every command broken**.

**To build, give a coding agent the repository**, then paste the build prompt for the edition you
are working on. Its first section verifies you have the right thing and stops if you do not.

## What is in here

| | File | What it is |
|---|---|---|
${rows.map((r) => '| ' + r.join(' | ') + ' |').join('\n')}

Every document is here twice: a \`.pdf\` to read and print, and a \`.md\` twin with the same content
as plain text for searching, sending or pasting.

**The two \`_PROMPT.md\` files are for an agent, the PDFs are for you.** An agent gains nothing from
a PDF that the markdown twin does not give it.

## About the screenshots

Every screen is a real render of the software — the same markup and stylesheet the product uses, not
a drawing of it. **The figures on them are illustrative**: representative examples, not a photograph
of anyone's live data.

Generated by \`brand/delivery/website/mkall.js\`. Nothing here is maintained by hand.
`;

const stage = fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'all-'));
files.forEach((f) => {
  const dest = path.join(stage, f);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(path.join(ROOT, f), dest);
});
fs.writeFileSync(path.join(stage, 'READ_ME_FIRST.md'), readme);
if (fs.existsSync(OUT)) fs.unlinkSync(OUT);
execFileSync('zip', ['-q', '-r', OUT, '.'], { cwd: stage });
fs.rmSync(stage, { recursive: true, force: true });

const mb = (fs.statSync(OUT).size / (1024 * 1024)).toFixed(1);
console.log(`${path.basename(OUT)}: ${files.length + 1} files · ${mb}MB · ` +
  `${M.editions().length} editions, every document in both forms`);
