'use strict';
/* THE STARTER KIT — an archive a coding agent can actually build from.
 *
 *   node brand/delivery/website/mkstarter.js            → MEDHAVA_STARTER.zip
 *   node brand/delivery/website/mkstarter.js --verify   → the same, then EXTRACT IT AND RUN IT
 *
 * WHY THIS EXISTS, AND WHY IT IS NOT MEDHAVA.zip
 * The delivery archives carry documents. That is what they are for, and it is why mkall.js opens
 * by saying they cannot build anything — a claim that was not a guess: extracting one and testing
 * the build prompt against it found 18 of its 22 paths absent and every command in it broken. A
 * document describes software. It does not produce it.
 *
 * This archive carries the REPOSITORY: the schema, the registers, the gates, the tests, the
 * toolchain lockfile, the working platform slice, and the working agreement that governs how they
 * are changed. An agent handed this has the thing the documents are about.
 *
 * THE ONE HONEST TEST OF A BUILD ARCHIVE IS TO BUILD FROM IT.
 * So --verify does not inspect the file list and conclude. It unzips into a scratch directory
 * nowhere near this repository, installs the toolchain, and runs the suite from the extract. What
 * it prints is that run's real exit code. Anything less is the same mistake in a new archive: an
 * assurance that the contents look right, which is exactly what was believed the last time.
 *
 * WHAT IS DELIBERATELY LEFT OUT
 *   node_modules   restored by `npm ci` from the committed lockfile, which is the point of a
 *                  lockfile. Shipping it would multiply the archive and pin one machine's
 *                  platform binaries.
 *   *.pdf          365MB of RENDERED documents, all regenerated by tools/report_pdf.py from
 *                  markdown that is in here. An agent reads the markdown.
 *   *.zip          202MB of archives, including this one's own siblings. An archive of archives.
 *   *.docx         one research file with no build role.
 *   ONE .html      the single rendered document among 72 tracked .html files. The other 71 are
 *                  source and stay — see isRenderedDocument() for why that is a rule and not a
 *                  list, and for what dropping all of them did.
 * Every exclusion is a thing that is DERIVED from something included, which is the test for
 * whether leaving it out loses anything.
 *
 * THE FILE LIST COMES FROM GIT, NOT A WALK.
 * `git ls-files` returns exactly what is committed — so nothing gitignored can be swept in, and
 * app/.env, app/data/ and every build artifact are excluded by construction rather than by a
 * pattern somebody has to remember to update. CLAUDE.md §4 requires that keys never reach an
 * artifact; this makes it structural instead of careful.
 */

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync, execSync } = require('node:child_process');

const ROOT = path.join(__dirname, '..', '..', '..');
const OUT = path.join(ROOT, 'MEDHAVA_STARTER.zip');
const STAGE = path.join(os.tmpdir(), 'medhava-starter-stage');

const verify = process.argv.includes('--verify');

const MODULES = require(path.join(ROOT, 'brand', 'site', 'modules.js'));
const RULES = require(path.join(ROOT, 'brand', 'site', 'rules.js'));
const PKG = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

/* Derived, never typed — the counts in the document this writes have already changed twice.
 *
 * AND A COUNT THAT CANNOT BE DERIVED STOPS THE BUILD. The first version of this reached for
 * RULES.RULES and RULES.ALL, found neither (rules.js exports the array itself), fell through to a
 * `|| 0` and printed "0 rules" into a document meant to tell somebody where the rulebook is.
 * Silently substituting zero for "I could not read it" is worse than typing the number, because a
 * typed number is at least wrong loudly. */
function derived(what, n) {
  if (!Number.isInteger(n) || n <= 0) {
    console.error(`mkstarter: could not derive ${what} — refusing to write a document that ` +
      `states a count it did not read. Fix the derivation, do not type the number.`);
    process.exit(1);
  }
  return n;
}

const NMODULES = derived('the module count', MODULES.length);
const NAPPS = derived('the app count', MODULES.reduce((n, m) => n + m.apps.length, 0));
const NRULES = derived('the rule count', Array.isArray(RULES) ? RULES.length : NaN);
const NTABLES = derived('the table count',
  (fs.readFileSync(path.join(ROOT, 'core', 'schema.postgres.sql'), 'utf8')
    .match(/^CREATE TABLE /gm) || []).length);

/* ── what goes in ────────────────────────────────────────────────────────── */

/* .html IS NOT A DOCUMENT FORMAT HERE, AND ASSUMING IT WAS BROKE THE ARCHIVE.
 * The first version dropped every .html alongside the .pdf and .zip output. That deleted
 * medhava/web/index.html — the application's own page — so the extracted archive served a 404
 * where the shell should be, and the browser suite failed five checks with confusing downstream
 * messages. It also deleted the 16 built prototype apps under brand/suite/out/.
 *
 * Of the 72 tracked .html files, exactly ONE is a rendered document. The rule that separates them
 * is not a list to maintain: a rendered document has a sibling .md of the same name, because that
 * is literally what tools/report_pdf.py made it from. Everything else is source. */
function isRenderedDocument(f) {
  if (!/\.html$/i.test(f)) return false;
  return fs.existsSync(path.join(ROOT, f.replace(/\.html$/i, '.md')));
}
const DROP = /\.(pdf|zip|docx)$/i;

function contents() {
  const tracked = execSync('git ls-files -z', { cwd: ROOT, maxBuffer: 64 * 1024 * 1024 })
    .toString('utf8').split('\0').filter(Boolean);
  return tracked.filter((f) => !DROP.test(f) && !isRenderedDocument(f));
}

/* ── the note that goes on top ───────────────────────────────────────────── */

function startHere() {
  return `# Medhava BOS — start here

## What this is

The **repository**, not a set of documents about it. Unzip it, open it with a coding agent, and
run the checks below. They either pass on your machine or they do not, and either way you will
know inside a few minutes — which is the only thing worth knowing before any work starts.

## First: prove you have a working copy

\`\`\`bash
npm ci                # the toolchain, from the committed lockfile
npm run test:source   # every gate, every register, and the platform slice
\`\`\`

That must end with **exit code 0**. If it does not, stop and read what failed — do not start
building on top of a red suite. The suite is not decoration: several of its checks were written by
planting the failure first and confirming the check caught it, and each one records what was
planted and what it said.

**Why \`test:source\` and not \`test\`.** \`npm test\` additionally runs \`checkcoverage\`, which
gates every delivered document against its rendered PDF. This archive ships no PDFs — they are
365MB of output regenerated from markdown that is here — so that gate has nothing to gate and
fails on all ten documents. It is the delivery gate, not a build gate. \`test:source\` is \`test\`
with exactly that one check removed and nothing else, which is asserted by the generator rather
than left to trust. Render the documents and \`npm test\` works too:

\`\`\`bash
npm run docs
python3 tools/report_pdf.py MEDHAVA_ARCHITECT.md
node tools/report_pdf.js MEDHAVA_ARCHITECT.html
\`\`\`

Then see it run:

\`\`\`bash
npm start     # http://localhost:4000
\`\`\`

Sign in as \`owner@anjali.demo\` (an apparel group, two companies) or \`owner@deccan.demo\` (a steel
works, one company) and open the **Isolation** page. It shows what your company can see against
what the database actually holds. Two unrelated businesses are in there at once.

## What is already built, and what is not

This matters more than anything else in this file, so it is stated before the architecture:

| | Count | State |
|---|---|---|
| Modules | ${NMODULES} | specified · a navigation page each |
| Apps | **${NAPPS}** | **0 built** |
| Business screens | 4 | built and working — Isolation, Channels, Products, Orders |
| API routes over business data | 4 | all \`GET\` — **nothing in the app can write yet** |
| Database tables | ${NTABLES} | built, running, isolated |

The platform underneath the apps is real: the schema executes into PostgreSQL, row-level security
is enforced by the database rather than by a filter the code remembered, sessions carry a tenant
and a company, and there is no exported way for a business query to reach the data without both.
That is what every one of the ${NAPPS} apps will stand on, and it is finished.

The apps themselves are not started. The module pages carry their real names, read from the
canonical list, and each says on screen that its screens are specified and not built. Leave that
mark in place until an app is genuinely built — a list of app names on a working shell reads as a
working app, and that is the one thing this project treats as cheating.

## Read CLAUDE.md before doing anything

\`CLAUDE.md\` in the root is the working agreement, and it is loaded automatically by Claude Code
at the start of every session. It exists because real work was rejected here for real reasons, and
those reasons are written down so they are not repeated. The two that catch people first:

- **Derive, never retype.** Counts and names come from the canonical source programmatically. A
  number typed from memory is treated as fabrication, and \`${NMODULES} modules\` has already
  changed twice.
- **Never claim something is finished when it is not.** Every deliverable is labelled tool, stub,
  mockup or spec, and it stays labelled even when a working version would show better.

## Where the truth lives

Do not restate these from memory. Read them.

| Truth | File |
|---|---|
| Modules, apps, order | \`brand/site/modules.js\` — the one canonical list |
| The production database | \`core/schema.postgres.sql\` |
| The ${NRULES} rules each module enforces | \`brand/site/rules.js\` |
| What each layer is built on, and its swaps | \`brand/site/stack.js\` |
| What a tenant can change | \`brand/site/dynamic.js\` |
| The running platform slice | \`medhava/\` |

## Building the first app

\`MEDHAVA_BOS_PROMPT.md\` is the build prompt. Its first section verifies you have the right thing
and stops if you do not — that check exists because an earlier archive of documents was handed to
an agent that started inventing files it could not find.

The order that works: pick one module, write its write-side routes and forms against the rules in
\`rules.js\`, and add a test for each rule that you prove fails before it passes. \`medhava/test/\`
is the worked example of that discipline — read \`isolation.test.js\` first, including the notes on
each check recording what was planted and what the check said when it caught it.

## What is not in this archive, and why

\`node_modules\` (restored by \`npm ci\`), the rendered \`.pdf\` and \`.html\` documents (regenerated
by \`tools/report_pdf.py\` from markdown that is here), and the delivery \`.zip\` archives. Each one
is derived from something included. Nothing you need to build is missing — which is checked by
this archive's own generator, not assumed: it extracts itself and runs the suite.
`;
}

/* ── the gate ────────────────────────────────────────────────────────────── */

function badCommand(cmd, has) {
  const parts = cmd.trim().split('\n')[0].trim().split(/\s+/);
  const [bin, a, b] = parts;
  if (bin === 'npm') {
    if (['ci', 'install', 'start', 'test'].includes(a)) return null;
    const script = a === 'run' ? b : a;
    if (!script) return 'names no npm script';
    return script in (PKG.scripts || {}) ? null : `npm script "${script}" is not in package.json`;
  }
  if (bin === 'node' || bin === 'python3') {
    if (!a) return `${bin} with no file`;
    return has.has(a) ? null : `${a} is not in the archive`;
  }
  if (bin === 'cd') return null;
  return null;
}

/** Every path and command the starter's own documents name must be IN the archive. */
function gate(files) {
  const has = new Set(files);
  const bad = [];

  /* The documents an agent is pointed at first. A path named in one of these that is not in the
     archive is the exact defect that made the document bundle unbuildable. */
  const speaks = ['START_HERE.md', 'CLAUDE.md', 'MEDHAVA_BOS_PROMPT.md'];
  for (const doc of speaks) {
    const text = doc === 'START_HERE.md' ? startHere()
      : has.has(doc) ? fs.readFileSync(path.join(ROOT, doc), 'utf8') : null;
    if (text === null) { bad.push(`${doc} is not in the archive`); continue; }

    /* Backticked things that look like repository paths — a slash and a known extension, or a
       bare directory. Deliberately narrow: a regex that guesses widely reports noise, and a gate
       that cries wolf gets switched off. */
    const cited = new Set([...text.matchAll(/`([A-Za-z0-9_./-]+\.(?:js|py|sql|json|md))`/g)]
      .map((m) => m[1]).filter((p) => p.includes('/') || has.has(p)));
    for (const p of cited) {
      if (!has.has(p)) bad.push(`${doc} names \`${p}\`, which is not in the archive`);
    }

    for (const m of text.matchAll(/```bash\n([\s\S]*?)```/g)) {
      for (const line of m[1].split('\n')) {
        const cmd = line.replace(/#.*$/, '').trim();
        if (!cmd) continue;
        const why = badCommand(cmd, has);
        if (why) bad.push(`${doc}: "${cmd}" — ${why}`);
      }
    }
  }

  /* The things without which nothing can be built at all, named individually so the failure says
     which one rather than "something is missing". */
  const MUST = [
    ['core/schema.postgres.sql', 'the database'],
    ['brand/site/modules.js', 'the canonical module list'],
    ['brand/site/rules.js', 'the rulebook'],
    ['package.json', 'the scripts'],
    ['package-lock.json', 'the toolchain, reproducibly'],
    ['CLAUDE.md', 'the working agreement'],
    ['medhava/server/db.js', 'the isolation the whole platform rests on'],
    ['medhava/test/isolation.test.js', 'the worked example of red-before-green'],
  ];
  for (const [p, why] of MUST) {
    if (!has.has(p)) bad.push(`${p} is missing — ${why}`);
  }

  /* Every npm script the starter tells somebody to run must name files that are present. */
  for (const [name, cmd] of Object.entries(PKG.scripts || {})) {
    for (const piece of cmd.split('&&')) {
      const why = badCommand(piece.trim(), has);
      if (why) bad.push(`npm script "${name}" runs "${piece.trim()}" — ${why}`);
    }
  }

  /* AND THE TWO CHECK SCRIPTS MUST NOT DRIFT.
     `check:source` exists for one reason: this archive ships no rendered PDFs, so checkcoverage —
     which gates DELIVERED DOCUMENTS against their PDFs — has nothing to gate and fails on all ten.
     It is the delivery gate, not a build gate. The danger is obvious: two lists of checks, and the
     next check added to one and not the other is silently not run by whoever uses this archive.
     So the relationship is asserted rather than trusted — `check:source` must be exactly `check`
     with checkcoverage removed, and nothing else. */
  const full = (PKG.scripts || {})['check'] || '';
  const src = (PKG.scripts || {})['check:source'] || '';
  const expected = full.split('&&').map((s) => s.trim())
    .filter((s) => !/checkcoverage\.js/.test(s)).join(' && ');
  if (src !== expected) {
    bad.push('npm "check:source" is not "check" minus checkcoverage. One of them has gained a ' +
      'check the other has not, and this archive would ship running the smaller list.\n' +
      `      expected: ${expected}\n      found:    ${src}`);
  }
  if (!/checkcoverage\.js/.test(full)) {
    bad.push('npm "check" no longer runs checkcoverage — then check:source has no reason to ' +
      'exist and the delivered documents are ungated. Delete one or restore the other.');
  }
  return bad;
}

/* ── build ───────────────────────────────────────────────────────────────── */

function stage(files) {
  fs.rmSync(STAGE, { recursive: true, force: true });
  const root = path.join(STAGE, 'medhava-bos');
  for (const f of files) {
    const dest = path.join(root, f);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(path.join(ROOT, f), dest);
  }
  fs.writeFileSync(path.join(root, 'START_HERE.md'), startHere());
  return root;
}

function main() {
  const files = contents();
  const bad = gate([...files, 'START_HERE.md']);
  if (bad.length) {
    console.error(`mkstarter: ${bad.length} problem(s) — this archive would not build:\n  ` +
      bad.join('\n  '));
    process.exit(1);
  }

  const root = stage(files);
  fs.rmSync(OUT, { force: true });
  execFileSync('zip', ['-qr', OUT, 'medhava-bos'], { cwd: STAGE, maxBuffer: 64 * 1024 * 1024 });

  const mb = (fs.statSync(OUT).size / 1024 / 1024).toFixed(1);
  console.log(`MEDHAVA_STARTER.zip written: ${mb}MB · ${files.length + 1} files`);
  console.log(`  ${NMODULES} modules · ${NAPPS} apps specified · ${NTABLES} tables · ` +
              `${NRULES} rules — every count read from source`);
  console.log(`  gate: every path and command in START_HERE, CLAUDE.md and the build prompt ` +
              `exists in the archive`);

  if (!verify) {
    console.log('\n  Run with --verify to extract it somewhere else and actually run the suite.');
    return;
  }

  /* ── the only test that means anything ─────────────────────────────────── */
  const box = fs.mkdtempSync(path.join(os.tmpdir(), 'starter-verify-'));
  console.log(`\n  verifying by extraction into ${box}`);
  execFileSync('unzip', ['-q', OUT, '-d', box]);
  const extracted = path.join(box, 'medhava-bos');

  /* npm ci needs the registry. Where it cannot be reached, the lockfile is still the right answer
     and the local install is a stand-in for it — but say which one happened, because "it built"
     means something different in each case. */
  let install = 'npm ci';
  try {
    execFileSync('npm', ['ci', '--no-audit', '--no-fund'],
      { cwd: extracted, stdio: 'pipe', timeout: 900000 });
  } catch (e) {
    install = 'copied node_modules (no registry reachable)';
    fs.cpSync(path.join(ROOT, 'node_modules'), path.join(extracted, 'node_modules'),
      { recursive: true });
  }
  console.log(`  toolchain: ${install}`);

  let code = 0, out = '';
  try {
    out = execFileSync('npm', ['run', 'test:source'],
      { cwd: extracted, encoding: 'utf8', timeout: 2400000 });
  } catch (e) { code = e.status === undefined ? 1 : e.status; out = (e.stdout || '') + (e.stderr || ''); }

  const tail = out.trim().split('\n').slice(-14).join('\n    ');
  console.log(`\n    ${tail}`);
  console.log(`\n  npm run test:source in the EXTRACTED archive: exit ${code}`);
  if (code === 0) {
    console.log('  The archive builds. Not inspected — extracted, installed and run.');
  } else {
    console.log('  The archive does NOT build. Fix that before sending it to anybody.');
  }
  process.exit(code);
}

main();
