/* Format A — Unified ERP (any industry). Neutral names; the same engine runs a machine shop,
   a distributor, an exporter or a professional practice. Only this file changes. */
var CONFIG={
  id:'m21_erp', name:'Module 21 · Dashboard & BI', company:'Acme Corp', fy:'FY 2026-27',
  tagline:'All three apps of Module 21 over one set of records — add, edit, delete, upload, and watch everything move.',
  about:'The CEO Dashboard, the Report Builder and Group Consolidation running on one shared set of records instead of three copies. Add a sale and the dashboard, every report and the group figures all move in the same instant, because there is only one set of numbers. Type records in, or upload an Excel or CSV file of them, or export the lot back out. This is the app to test with: anything you can do here, the three separate apps do on the same engine.',
  companies:[
    {id:'AMF',name:'Acme Manufacturing Pvt Ltd',gstin:'27AACCA1234F1Z5',note:'Makes and sells the main product line'},
    {id:'AEX',name:'Acme Exports LLP',gstin:'24AAFCA9876B1Z2',note:'Overseas orders and distribution'},
    {id:'AWK',name:'Acme Workshop',gstin:'',note:'Does job work for the other two — it has no tax registration of its own'}],
  brands:[
    {name:'Acme Direct',co:'AMF',where:'Own storefront'},
    {name:'AcmePro',co:'AMF',where:'Marketplace seller name — every order is invoiced as Acme Manufacturing'},
    {name:'Acme Global',co:'AEX',where:'Export documents'}],
  plan:{name:'Enterprise',companyCap:20},
  costHeads:['Marketing','Logistics'],
  icNote:'Assembly work done for the selling companies',
  icChannel:'Between our own companies',
  channels:['Retail Stores','Online Marketplace','Own Website','Wholesale / B2B','Export'],
  items:[
    {sku:'ITM-01',co:'AMF',name:'Primary raw material',qty:820,rop:400,cost:280},
    {sku:'ITM-02',co:'AMF',name:'Secondary raw material',qty:310,rop:350,cost:90},
    {sku:'ITM-03',co:'AMF',name:'Precision component',qty:1450,rop:600,cost:150},
    {sku:'ITM-04',co:'AWK',name:'Lining / substrate',qty:180,rop:250,cost:35},
    {sku:'ITM-05',co:'AWK',name:'Finishing consumable',qty:640,rop:200,cost:210},
    {sku:'FG-101',co:'AMF',name:'Finished product — standard',qty:96,rop:120,cost:1180},
    {sku:'FG-102',co:'AEX',name:'Finished product — premium',qty:240,rop:100,cost:2260},
    {sku:'PKG-01',co:'AEX',name:'Packaging set',qty:2100,rop:800,cost:22}],
  parties:{
    r:['Northline Retail Pvt Ltd','Metro Distributors','Harbour Trading Co','Sunrise Enterprises'],
    p:['Alpha Industrial Supplies','Beta Components Ltd','Gamma Materials Co','Delta Trading']},
  templates:[
    {name:'Which channel actually earns the most?',
     why:'Busy is not the same as profitable. This ranks every channel by net sales — after returns are taken off.',
     def:{src:'sales',group:'channel',sort:'net',dir:'desc',limit:0,filters:[]}},
    {name:'Which company is carrying the group?',
     why:'The same sales, grouped by company instead of channel. The totals are identical; the story is not.',
     def:{src:'sales',group:'company',sort:'net',dir:'desc',limit:0,filters:[]}},
    {name:'Where are returns eating the profit?',
     why:'Shows only the bigger channels so the return figure next to gross is worth reading.',
     def:{src:'sales',group:'channel',sort:'returns',dir:'desc',limit:0,filters:[{field:'gross',op:'>=',val:'40000'}]}},
    {name:'How is each month trending?',
     why:'Net sales month by month, oldest to newest, so a dip is obvious.',
     def:{src:'sales',group:'monthLabel',sort:'label',dir:'asc',limit:0,filters:[]}},
    {name:'Who has not paid me?',
     why:'Only money coming in, biggest first — your collection call list for the week.',
     def:{src:'money',group:'party',sort:'amount',dir:'desc',limit:0,filters:[{field:'type',op:'is',val:'To collect'}]}},
    {name:'What am I about to be chased for?',
     why:'Supplier bills already past their due date, worst first.',
     def:{src:'money',group:'party',sort:'days',dir:'desc',limit:0,filters:[{field:'type',op:'is',val:'To pay'},{field:'days',op:'>',val:'0'}]}},
    {name:'Where is my money sitting in stock?',
     why:'Top 5 items by value at cost — usually where the cash has quietly gone.',
     def:{src:'stock',group:'name',sort:'value',dir:'desc',limit:5,filters:[]}},
    {name:'What do I have to reorder now?',
     why:'Only items at or below their reorder point. This is a purchase list, not a warning.',
     def:{src:'stock',group:'name',sort:'qty',dir:'asc',limit:0,filters:[{field:'status',op:'is',val:'Reorder now'}]}},
    {name:'What are my biggest running costs?',
     why:'Every cost head added up across the year, biggest first.',
     def:{src:'expenses',group:'cat',sort:'amount',dir:'desc',limit:0,filters:[]}},
    {name:'Which supplier am I most exposed to?',
     why:'Everything bought in, by supplier. One name near the top of this list is a risk worth knowing about.',
     def:{src:'purchases',group:'party',sort:'amount',dir:'desc',limit:0,filters:[]}},
    {name:'Is the floor getting cheaper or dearer?',
     why:'Pieces made and wages paid, month by month — divide one by the other to see cost per piece moving.',
     def:{src:'production',group:'monthLabel',sort:'label',dir:'asc',limit:0,filters:[]}}],
  wiring:[
    {f:'Everything you type or upload',s:'This app',h:'Records are written once, in one place, and every screen reads them from there'},
    {f:'Overview, Sales, Money, Stock, Alerts',s:'Sales + Purchase + Inventory &amp; Catalog + Manufacturing + Accounting &amp; GST',h:'The CEO Dashboard screens, on the records in this app'},
    {f:'Build a report',s:'This app + Sales',h:'The Report Builder, reading the same records — a report can never disagree with the dashboard'},
    {f:'Group roll-up',s:'Platform (companies) + Accounting &amp; GST',h:'Group Consolidation, on the same records, with inter-company billing removed'},
    {f:'Upload Excel or CSV',s:'This app',h:'Column headings are matched to fields, every row is checked, and anything rejected is shown with its reason'},
    {f:'Download Excel or CSV',s:'This app',h:'Every table written back out as a sheet, ready to hand to anybody'}],
  wiringIn:[
    {from:'Sales',what:'Invoices and credit notes with their channel and company'},
    {from:'Purchase',what:'Supplier bills per company'},
    {from:'Inventory',what:'Quantity on hand, cost, reorder point'},
    {from:'Manufacturing',what:'Pieces produced and wages booked'},
    {from:'Accounting &amp; GST',what:'Opening balances, expenses, receipts and payments'},
    {from:'Platform',what:'Companies, trading names and the plan you are on'}]
};
