/* Format A — Unified ERP (any industry). Neutral names; the same engine runs a machine shop,
   a distributor, an exporter or a professional practice. Only this file changes. */
var CONFIG={
  id:'reports_erp', name:'Report Builder', company:'Acme Corp', fy:'FY 2026-27',
  tagline:'Ask any question of your own data — pick, group, filter, run. No formulas, no waiting.',
  about:'A report writer built for someone who does not write formulas. Choose what to look at (sales, money owed, stock, running costs, production, purchases), choose how to group it — including by company — leave out what you do not want, and the answer appears immediately. Save the question, not the answer, and it recalculates on fresh data every time you run it. Everything downloads as CSV or Excel.',
  companies:[
    {id:'AMF',name:'Acme Manufacturing Pvt Ltd',gstin:'27AACCA1234F1Z5',note:'Makes and sells the main product line'},
    {id:'AEX',name:'Acme Exports LLP',gstin:'24AAFCA9876B1Z2',note:'Overseas orders and distribution'},
    {id:'AWK',name:'Acme Workshop',gstin:'',note:'Does job work for the other two — it has no tax registration of its own'}],
  brands:[
    {name:'Acme Direct',co:'AMF',where:'Own storefront'},
    {name:'AcmePro',co:'AMF',where:'Marketplace seller name — every order is invoiced as Acme Manufacturing'},
    {name:'Acme Global',co:'AEX',where:'Export documents'}],
  plan:{name:'Enterprise',companyCap:20},
  costHeads:['Marketing','Logistics'],
  icNote:'Assembly work done for the selling companies',
  icChannel:'Between our own companies',
  channels:['Retail Stores','Online Marketplace','Own Website','Wholesale / B2B','Export'],
  items:[
    {sku:'ITM-01',co:'AMF',name:'Primary raw material',qty:820,rop:400,cost:280},
    {sku:'ITM-02',co:'AMF',name:'Secondary raw material',qty:310,rop:350,cost:90},
    {sku:'ITM-03',co:'AMF',name:'Precision component',qty:1450,rop:600,cost:150},
    {sku:'ITM-04',co:'AWK',name:'Lining / substrate',qty:180,rop:250,cost:35},
    {sku:'ITM-05',co:'AWK',name:'Finishing consumable',qty:640,rop:200,cost:210},
    {sku:'FG-101',co:'AMF',name:'Finished product — standard',qty:96,rop:120,cost:1180},
    {sku:'FG-102',co:'AEX',name:'Finished product — premium',qty:240,rop:100,cost:2260},
    {sku:'PKG-01',co:'AEX',name:'Packaging set',qty:2100,rop:800,cost:22}],
  parties:{
    r:['Northline Retail Pvt Ltd','Metro Distributors','Harbour Trading Co','Sunrise Enterprises'],
    p:['Alpha Industrial Supplies','Beta Components Ltd','Gamma Materials Co','Delta Trading']},
  templates:[
    {name:'Which channel actually earns the most?',
     why:'Busy is not the same as profitable. This ranks every channel by net sales — after returns are taken off.',
     def:{src:'sales',group:'channel',sort:'net',dir:'desc',limit:0,filters:[]}},
    {name:'Which company is carrying the group?',
     why:'The same sales, grouped by company instead of channel. The totals are identical; the story is not.',
     def:{src:'sales',group:'company',sort:'net',dir:'desc',limit:0,filters:[]}},
    {name:'Where are returns eating the profit?',
     why:'Shows only the bigger channels so the return figure next to gross is worth reading.',
     def:{src:'sales',group:'channel',sort:'returns',dir:'desc',limit:0,filters:[{field:'gross',op:'>=',val:'40000'}]}},
    {name:'How is each month trending?',
     why:'Net sales month by month, oldest to newest, so a dip is obvious.',
     def:{src:'sales',group:'monthLabel',sort:'label',dir:'asc',limit:0,filters:[]}},
    {name:'Who has not paid me?',
     why:'Only money coming in, biggest first — your collection call list for the week.',
     def:{src:'money',group:'party',sort:'amount',dir:'desc',limit:0,filters:[{field:'type',op:'is',val:'To collect'}]}},
    {name:'What am I about to be chased for?',
     why:'Supplier bills already past their due date, worst first.',
     def:{src:'money',group:'party',sort:'days',dir:'desc',limit:0,filters:[{field:'type',op:'is',val:'To pay'},{field:'days',op:'>',val:'0'}]}},
    {name:'Where is my money sitting in stock?',
     why:'Top 5 items by value at cost — usually where the cash has quietly gone.',
     def:{src:'stock',group:'name',sort:'value',dir:'desc',limit:5,filters:[]}},
    {name:'What do I have to reorder now?',
     why:'Only items at or below their reorder point. This is a purchase list, not a warning.',
     def:{src:'stock',group:'name',sort:'qty',dir:'asc',limit:0,filters:[{field:'status',op:'is',val:'Reorder now'}]}},
    {name:'What are my biggest running costs?',
     why:'Every cost head added up across the year, biggest first.',
     def:{src:'expenses',group:'cat',sort:'amount',dir:'desc',limit:0,filters:[]}},
    {name:'Which supplier am I most exposed to?',
     why:'Everything bought in, by supplier. One name near the top of this list is a risk worth knowing about.',
     def:{src:'purchases',group:'party',sort:'amount',dir:'desc',limit:0,filters:[]}},
    {name:'Is the floor getting cheaper or dearer?',
     why:'Pieces made and wages paid, month by month — divide one by the other to see cost per piece moving.',
     def:{src:'production',group:'monthLabel',sort:'label',dir:'asc',limit:0,filters:[]}}],
  wiring:[
    {f:'Sales',s:'Sales',h:'One row per company per channel per month — gross, returns, net and units'},
    {f:'Money owed',s:'Accounts Receivable + Accounts Payable',h:'One row per unpaid customer invoice or supplier bill, with its age in days'},
    {f:'Stock',s:'Inventory &amp; Catalog',h:'One row per item — quantity on hand, cost, reorder point and value'},
    {f:'Running costs',s:'Accounting &amp; GST (expense vouchers)',h:'One row per cost head per month — rent, salaries, marketing, logistics'},
    {f:'Production',s:'Manufacturing',h:'One row per company per month — pieces finished and wages booked by the floor'},
    {f:'Purchases',s:'Purchase',h:'One row per supplier per month — what you bought in'}],
  wiringIn:[
    {from:'Sales',what:'Invoices and credit notes with their channel tag'},
    {from:'Accounting &amp; GST',what:'Unpaid invoices, unpaid bills, expense vouchers'},
    {from:'Inventory',what:'Quantity on hand, cost price, reorder point'},
    {from:'Manufacturing',what:'Pieces produced and wages booked'},
    {from:'Purchase',what:'Supplier bills, month by month'},
    {from:'Platform',what:'Which companies exist, so any report can be grouped by company'},
    {from:'CEO Dashboard',what:'Uses the same engine, so a report always agrees with the dashboard'}]
};
