/* Format B — Vastrangam. Its own companies, seller names, mills and marketplaces — the same
   engine as the neutral edition, carrying a real business so the neutrality can be tested. */
var CONFIG={
  id:'reports_vastrangam', name:'Report Builder', company:'Vastrangam', fy:'FY 2026-27',
  tagline:'Ask the group’s own data anything — Myntra vs Flipkart, fabric stuck in stock, mills unpaid.',
  about:'A report writer that does not need formulas. Choose what to look at (marketplace sales, money owed, fabric and finished stock, running costs, karigar output, mill purchases), choose how to group it — including by company — leave out what you do not want, and the answer appears immediately. Marketplace returns are always taken off before anything is called “net”, so a channel never looks better than it is. Save the question, not the answer, and it recalculates every time. Download as CSV or Excel for the CA.',
  companies:[
    {id:'EF',name:'Ethnic Fashion',gstin:'24AABFE1234K1Z9',note:'The Go4Fashion brand'},
    {id:'VG',name:'Vastrangam',gstin:'24AAAFV5678M1Z3',note:'Sells under both the Vastrangam and the Adini seller names'},
    {id:'AC',name:'Adini Couture',gstin:'',note:'Job work for the other two — it has no tax registration of its own'}],
  brands:[
    {name:'Go4Fashion',co:'EF',where:'Own website and marketplace listings'},
    {name:'Vastrangam',co:'VG',where:'Marketplace seller name'},
    {name:'Adini',co:'VG',where:'Marketplace seller name — every order is invoiced as Vastrangam'}],
  plan:{name:'Enterprise',companyCap:20},
  costHeads:['Ad spend','Courier'],
  icNote:'Stitching done for the selling companies',
  icChannel:'Between our own companies',
  channels:['Myntra','Flipkart','Own Website','Wholesale (Surat)','Exhibition / Exports'],
  items:[
    {sku:'FAB-SILK',co:'EF',name:'Banarasi silk fabric (m)',qty:820,rop:400,cost:280},
    {sku:'FAB-COT',co:'EF',name:'Cotton fabric 44" (m)',qty:310,rop:350,cost:90},
    {sku:'ZARI-01',co:'AC',name:'Zari thread (reel)',qty:1450,rop:600,cost:150},
    {sku:'LIN-01',co:'AC',name:'Cotton lining (m)',qty:180,rop:250,cost:35},
    {sku:'GOTA-01',co:'AC',name:'Gota / dye finishing (kg)',qty:640,rop:200,cost:210},
    {sku:'VS-KUR-01',co:'VG',name:'Cotton kurta set — ready',qty:96,rop:120,cost:1180},
    {sku:'VS-SAR-02',co:'VG',name:'Banarasi saree — ready',qty:240,rop:100,cost:2260},
    {sku:'PKG-01',co:'VG',name:'Poly bag + tag + box',qty:2100,rop:800,cost:22}],
  parties:{
    r:['Myntra (Myntra Designs Pvt Ltd)','Flipkart (Flipkart India)','Surat Wholesale — Rajmandir','Exhibition buyer — Dubai'],
    p:['Jagdamba Textiles (Surat)','Kanchi Silks','Surat Cotton Mills','Zari Works Jaipur']},
  templates:[
    {name:'Myntra or Flipkart — which one actually pays?',
     why:'Ranks every channel by net sales after returns. Flipkart looks big on gross and much smaller on net; this is the report that proves it.',
     def:{src:'sales',group:'channel',sort:'net',dir:'desc',limit:0,filters:[]}},
    {name:'Which company is carrying the group?',
     why:'The same sales, grouped by company instead of channel. Ethnic Fashion, Vastrangam and Adini Couture, side by side.',
     def:{src:'sales',group:'company',sort:'net',dir:'desc',limit:0,filters:[]}},
    {name:'Where are returns eating the margin?',
     why:'Returns by channel, only counting the lines that were big enough to matter. Anything over 12% is a listing or fit problem, not bad luck.',
     def:{src:'sales',group:'channel',sort:'returns',dir:'desc',limit:0,filters:[{field:'gross',op:'>=',val:'40000'}]}},
    {name:'How is the season trending?',
     why:'Net sales month by month from April, so a festive build-up or a dip shows up before the quarter closes.',
     def:{src:'sales',group:'monthLabel',sort:'label',dir:'asc',limit:0,filters:[]}},
    {name:'Which settlements are still stuck?',
     why:'Money the marketplaces and wholesale buyers still owe, biggest first — the follow-up list for the week.',
     def:{src:'money',group:'party',sort:'amount',dir:'desc',limit:0,filters:[{field:'type',op:'is',val:'To collect'}]}},
    {name:'Which mills are already past due?',
     why:'Fabric and zari bills that have crossed their agreed terms, worst first. Paying these on time is what keeps the rate you negotiated.',
     def:{src:'money',group:'party',sort:'days',dir:'desc',limit:0,filters:[{field:'type',op:'is',val:'To pay'},{field:'days',op:'>',val:'0'}]}},
    {name:'Where is the cash sitting in fabric?',
     why:'Top 5 items by value at cost. In this business the answer is almost always silk — this shows how much.',
     def:{src:'stock',group:'name',sort:'value',dir:'desc',limit:5,filters:[]}},
    {name:'What must be reordered before the next cut?',
     why:'Only fabric and SKUs at or below their reorder point. This is the purchase list that stops the karigar floor going idle.',
     def:{src:'stock',group:'name',sort:'qty',dir:'asc',limit:0,filters:[{field:'status',op:'is',val:'Reorder now'}]}},
    {name:'What are the biggest running costs?',
     why:'Rent, salaries, ad spend and courier added up across the year, biggest first. Ad spend is usually the one that grew without anyone deciding.',
     def:{src:'expenses',group:'cat',sort:'amount',dir:'desc',limit:0,filters:[]}},
    {name:'Which mill am I most exposed to?',
     why:'Everything bought in, by mill. One name near the top of this list is a risk worth knowing about before the next season.',
     def:{src:'purchases',group:'party',sort:'amount',dir:'desc',limit:0,filters:[]}},
    {name:'Is the karigar floor getting cheaper or dearer?',
     why:'Pieces finished and wages paid, month by month. Wages rising faster than pieces means the cost per piece is climbing.',
     def:{src:'production',group:'monthLabel',sort:'label',dir:'asc',limit:0,filters:[]}}],
  wiring:[
    {f:'Sales',s:'E-commerce / OMS + Sales',h:'One row per company per channel per month — gross, returns, net and units'},
    {f:'Money owed',s:'Settlement + Purchase (mill bills)',h:'One row per pending settlement or unpaid mill bill, with its age in days'},
    {f:'Stock',s:'Inventory &amp; Catalog (fabric and finished)',h:'One row per fabric or SKU — metres/pieces on hand, cost, reorder point and value'},
    {f:'Running costs',s:'Accounting &amp; GST (expense vouchers)',h:'One row per cost head per month — rent, salaries, ad spend, courier'},
    {f:'Production',s:'Manufacturing (karigar floor)',h:'One row per company per month — pieces finished and wages booked by the tailoring unit'},
    {f:'Purchases',s:'Purchase',h:'One row per mill per month — fabric, zari and trims bought in'}],
  wiringIn:[
    {from:'E-commerce / OMS',what:'Marketplace and website orders, returns and settlements'},
    {from:'Accounting &amp; GST',what:'Unpaid settlements, mill bills, expense vouchers'},
    {from:'Inventory',what:'Fabric metres, finished pieces, cost, reorder point'},
    {from:'Manufacturing (karigar)',what:'Pieces finished and wages booked'},
    {from:'Purchase',what:'Mill bills, month by month'},
    {from:'Platform',what:'Which companies exist, so any report can be grouped by company'},
    {from:'CEO Dashboard',what:'Uses the same engine, so a report always agrees with the dashboard'}]
};
