/* Format B — Vastrangam (ethnic-wear D2C + marketplace, textile). Real channels, fabrics, karigars, Surat–Jaipur supply base. */
var CONFIG={
  id:'reports_vastrangam', name:'Report Builder', company:'Vastrangam', fy:'FY 2026-27',
  tagline:'Ask Vastrangam’s own data anything — Myntra vs Flipkart, fabric stuck in stock, mills unpaid.',
  about:'A report writer for Vastrangam that does not need formulas. Choose what to look at (marketplace sales, money owed, fabric and finished stock, running costs, karigar output), choose how to group it, leave out what you do not want, and the answer appears immediately. Myntra and Flipkart returns are always taken off before anything is called “net”, so a channel never looks better than it is. Save the question — not the answer — and it recalculates on fresh data every time. Download any report as CSV for Excel or for the CA.',
  channels:['Myntra','Flipkart','Own Website','Wholesale (Surat)','Exhibition / Exports'],
  items:[
    {sku:'FAB-SILK',name:'Banarasi silk fabric (m)',qty:820,rop:400,cost:280},
    {sku:'FAB-COT',name:'Cotton fabric 44" (m)',qty:310,rop:350,cost:90},
    {sku:'ZARI-01',name:'Zari thread (reel)',qty:1450,rop:600,cost:150},
    {sku:'LIN-01',name:'Cotton lining (m)',qty:180,rop:250,cost:35},
    {sku:'GOTA-01',name:'Gota / dye finishing (kg)',qty:640,rop:200,cost:210},
    {sku:'VS-KUR-01',name:'Cotton kurta set — ready',qty:96,rop:120,cost:1180},
    {sku:'VS-SAR-02',name:'Banarasi saree — ready',qty:240,rop:100,cost:2260},
    {sku:'PKG-01',name:'Poly bag + tag + box',qty:2100,rop:800,cost:22}],
  parties:{
    r:['Myntra (Myntra Designs Pvt Ltd)','Flipkart (Flipkart India)','Surat Wholesale — Rajmandir','Exhibition buyer — Dubai'],
    p:['Jagdamba Textiles (Surat)','Kanchi Silks','Surat Cotton Mills','Zari Works Jaipur']},
  templates:[
    {name:'Myntra or Flipkart — which one actually pays?',
     why:'Ranks every channel by net sales after returns. Flipkart looks big on gross and much smaller on net; this is the report that proves it.',
     def:{src:'sales',group:'channel',sort:'net',dir:'desc',limit:0,filters:[]}},
    {name:'Where are returns eating the margin?',
     why:'Returns by channel, only counting the months that were big enough to matter. Anything over 12% is a listing or fit problem, not bad luck.',
     def:{src:'sales',group:'channel',sort:'returns',dir:'desc',limit:0,filters:[{field:'gross',op:'>=',val:'60000'}]}},
    {name:'How is the season trending?',
     why:'Net sales month by month from April, so a festive build-up or a dip shows up before the quarter closes.',
     def:{src:'sales',group:'monthLabel',sort:'label',dir:'asc',limit:0,filters:[]}},
    {name:'Which settlements are still stuck?',
     why:'Money the marketplaces and wholesale buyers still owe, biggest first — the follow-up list for the week.',
     def:{src:'money',group:'party',sort:'amount',dir:'desc',limit:0,filters:[{field:'type',op:'is',val:'To collect'}]}},
    {name:'Which mills are already past due?',
     why:'Fabric and zari bills that have crossed their agreed terms, worst first. Paying these on time is what keeps the rate you negotiated.',
     def:{src:'money',group:'party',sort:'days',dir:'desc',limit:0,filters:[{field:'type',op:'is',val:'To pay'},{field:'days',op:'>',val:'0'}]}},
    {name:'Where is the cash sitting in fabric?',
     why:'Top 5 items by value at cost. In this business the answer is almost always silk — this shows how much.',
     def:{src:'stock',group:'name',sort:'value',dir:'desc',limit:5,filters:[]}},
    {name:'What must be reordered before the next cut?',
     why:'Only fabric and SKUs at or below their reorder point. This is the purchase list that stops the karigar floor going idle.',
     def:{src:'stock',group:'name',sort:'qty',dir:'asc',limit:0,filters:[{field:'status',op:'is',val:'Reorder now'}]}},
    {name:'What are the biggest running costs?',
     why:'Rent, salaries, ad spend and courier added up across the year, biggest first. Ad spend is usually the one that grew without anyone deciding.',
     def:{src:'expenses',group:'cat',sort:'amount',dir:'desc',limit:0,filters:[]}},
    {name:'Is the karigar floor getting cheaper or dearer?',
     why:'Pieces finished and wages paid, month by month. Wages rising faster than pieces means the cost per piece is climbing.',
     def:{src:'production',group:'monthLabel',sort:'label',dir:'asc',limit:0,filters:[]}}],
  wiring:[
    {f:'Sales',s:'E-commerce / OMS + Sales',h:'One row for each channel in each month — gross, returns, net and units'},
    {f:'Money owed',s:'Settlement + Purchase (mill bills)',h:'One row per pending settlement or unpaid mill bill, with its age in days'},
    {f:'Stock',s:'Inventory &amp; Catalog (fabric and finished)',h:'One row per fabric or SKU — metres/pieces on hand, cost, reorder point and value'},
    {f:'Running costs',s:'Accounting &amp; GST (expense vouchers)',h:'One row per cost head per month — rent, salaries, ad spend, courier'},
    {f:'Production',s:'Manufacturing (karigar floor)',h:'One row per month — pieces finished and wages booked by the tailoring unit'}],
  wiringIn:[
    {from:'E-commerce / OMS',what:'Myntra / Flipkart / website orders, returns and settlements'},
    {from:'Accounting &amp; GST',what:'Unpaid settlements, mill bills, expense vouchers'},
    {from:'Inventory',what:'Fabric metres, finished pieces, cost, reorder point'},
    {from:'Manufacturing (karigar)',what:'Pieces finished and wages booked'},
    {from:'CEO Dashboard',what:'Uses the same rules, so a report always agrees with the dashboard'}]
};
