/* Format A — Unified ERP (any industry). Neutral names; drop-in for anyone who quotes before selling. */
var CONFIG={
  id:'quotes_erp', name:'Quotes & Proforma', company:'Acme Corp', fy:'FY 2026-27', prefix:'QT-',
  tagline:'A quote is a promise with an expiry date — and every revision is kept.',
  about:'Send a quote, revise it as the customer haggles, and turn the accepted one into a proforma and then a confirmed order in one click each, with nothing re-typed. Two things make this worth having. First, a quote expires by itself the day its validity runs out — nobody has to remember, and nobody can honour a three-month-old price by accident. Second, every revision is kept: the customer only ever sees the latest, but you can always see the first, which is the only way to answer "what did discounting cost us this quarter".',
  ph:{cust:'e.g. Northline Retail Pvt Ltd'},
  items:[
    {sku:'FG-101',name:'Standard product',rate:1200},
    {sku:'FG-102',name:'Premium product',rate:3400},
    {sku:'FG-103',name:'Accessory',rate:600},
    {sku:'FG-104',name:'Top-of-range product',rate:8900}],
  quotes:[
    {id:'QT-301',cust:'Northline Retail Pvt Ltd',date:'2026-07-26',validity:15,status:'sent',
     revs:[{lines:[{sku:'FG-102',name:'Premium product',rate:3400,qty:60}],disc:5,why:'First offer'},
           {lines:[{sku:'FG-102',name:'Premium product',rate:3400,qty:60}],disc:9,why:'Revised at the customer’s request'},
           {lines:[{sku:'FG-102',name:'Premium product',rate:3400,qty:50}],disc:12,why:'Revised at the customer’s request'}]},
    {id:'QT-302',cust:'Metro Distributors',date:'2026-07-30',validity:7,status:'sent',
     revs:[{lines:[{sku:'FG-101',name:'Standard product',rate:1200,qty:150}],disc:8,why:'First offer'}]},
    {id:'QT-303',cust:'Harbour Trading Co',date:'2026-06-18',validity:15,status:'sent',
     revs:[{lines:[{sku:'FG-104',name:'Top-of-range product',rate:8900,qty:12}],disc:4,why:'First offer'}]},
    {id:'QT-304',cust:'Sunrise Enterprises',date:'2026-07-20',validity:30,status:'accepted',acceptedOn:'2026-07-24',
     revs:[{lines:[{sku:'FG-103',name:'Accessory',rate:600,qty:300}],disc:6,why:'First offer'},
           {lines:[{sku:'FG-103',name:'Accessory',rate:600,qty:300}],disc:10,why:'Revised at the customer’s request'}]},
    {id:'QT-305',cust:'Crestline Traders',date:'2026-07-11',validity:30,status:'proforma',acceptedOn:'2026-07-15',
     revs:[{lines:[{sku:'FG-101',name:'Standard product',rate:1200,qty:80}],disc:4,why:'First offer'}]},
    {id:'QT-306',cust:'Orchid Retail',date:'2026-06-30',validity:15,status:'order',acceptedOn:'2026-07-04',
     revs:[{lines:[{sku:'FG-102',name:'Premium product',rate:3400,qty:35}],disc:8,why:'First offer'}]},
    {id:'QT-307',cust:'Bluestone Mart',date:'2026-07-08',validity:15,status:'lost',
     revs:[{lines:[{sku:'FG-104',name:'Top-of-range product',rate:8900,qty:8}],disc:5,why:'First offer'},
           {lines:[{sku:'FG-104',name:'Top-of-range product',rate:8900,qty:8}],disc:14,why:'Revised at the customer’s request'}]},
    {id:'QT-308',cust:'Coastal Wholesale',date:'2026-07-29',validity:30,status:'draft',
     revs:[{lines:[{sku:'FG-103',name:'Accessory',rate:600,qty:200}],disc:0,why:'First offer'}]}],
  slipNote:'This table is the reason to keep revisions at all. One quote losing 10% is a negotiation; every quote losing 10% is a price list that is 10% too high, and nobody notices unless somebody keeps the first offer.',
  wiring:[
    {f:'Item rate on a quote',s:'Catalog',h:'Read from the price list, not typed by whoever raised it'},
    {f:'Line total',s:'This app',h:'Quantity × the catalog rate'},
    {f:'Discount',s:'This app',h:'A percentage of gross, capped at 50%, kept per revision'},
    {f:'GST',s:'This app + tax rules',h:'5% of the value after discount, never on the gross'},
    {f:'Quote total',s:'This app',h:'Taxable value + GST, always from the latest revision'},
    {f:'Expiry date',s:'This app',h:'The date raised plus the validity chosen. Worked out, never stored or updated'},
    {f:'Expired',s:'This app',h:'Any unaccepted quote whose expiry date has passed — decided by the calendar, not by a person'},
    {f:'What came off',s:'This app',h:'The first revision’s total minus the current one’s'},
    {f:'Win rate',s:'This app',h:'Accepted ÷ (accepted + lost). Expired quotes are not counted as lost until you say so'},
    {f:'Confirmed order',s:'Sales / Orders',h:'The quote leaves this app; stock is reserved and the books take over'}],
  wiringIn:[
    {from:'Catalog',what:'Every item and its list price'},
    {from:'CRM',what:'Who the customer is and what they have bought before'},
    {from:'Inventory',what:'Whether the quantity quoted can actually be supplied'},
    {from:'Sales & Orders',what:'Takes the confirmed order once the quote is converted'},
    {from:'Accounting',what:'The proforma and then the invoice'}]
};
