/* ═══════════ Vastrangam AI Engine — market analysis Doc + AI prose upgrade ═══════════
   The second output format the user asked for: a Doc with market analysis, trends, competitor
   analysis, gap analysis and "what I can do better". Built offline from the libraries and the
   product; upgraded by a connected model when one is set. Downloads as a Word-openable .doc. */
(function () {
  'use strict';
  var DB = function () { return VA.DB; };

  function analysis(p) {
    var occ = p.occ.replace('-', ' '), typeNoun = p.typeNoun, colour = p.colour, fabric = p.fabric, work = p.work;
    var floor = { 'Anarkali Suit': 779, 'Lehenga Choli': 1200, 'Saree': 650, 'Kurti': 220, 'Sharara Set': 900, 'Palazzo Set': 700, 'Salwar Suit Set': 650, 'Dress (Western)': 350 }[p.cat] || 700;
    return {
      title: colour + ' ' + p.cat + ' — Market & Competitive Analysis',
      market: 'This is a Surat-made design family, resold widely across value→premium. At catalogue quantity the ' + p.cat.toLowerCase() + ' construction lands near ₹' + floor + '/piece; the same design retails from marketplaces at the value end up to designer houses at multiples of that. You are not competing on the product — everyone can buy the same catalogue. You compete on fit, story, photography and trust.',
      trends: [
        colour + ' is a searched shade for ' + occ + ' — name it in the title, not just "' + fabric.toLowerCase() + ' ' + typeNoun.toLowerCase() + '".',
        'Buyers compare spec sheets: publish flare in metres, dupatta length, weight in grams — most listings give nothing to compare.',
        'Custom-fit XS–3XL is a structural edge over value sellers who ship four sizes and hope.',
        'Real-place photography (not flat-lay) reads a full price band higher; the detail/back shot is what sells ' + work.toLowerCase() + '.'
      ],
      competitors: [
        { tier: 'Value (Meesho, Flipkart pool)', how: 'lists it as "embroidered ' + typeNoun.toLowerCase() + ' with dupatta"; wins on price + COD', beat: 'do not chase them on price — beat them on trust (real photos, custom-fit)' },
        { tier: 'Mid (cbazaar, Mirraw, Indo Era)', how: 'faux georgette, heavy discounting, generic titles', beat: 'name the occasion + the trims (' + work.toLowerCase() + ', moti hem); undercut on price while beating on sizes' },
        { tier: 'Premium (Kalki, Pernia\'s, Lashkaraa)', how: 'owns the search phrase, ships weeks out', beat: 'take their Google traffic with the words they don\'t use, and win on same-week dispatch' }
      ],
      gaps: [
        'Nobody names what ' + colour.toLowerCase() + ' is FOR at a ' + occ + ' — the single most searchable true thing.',
        'Nobody names the trims — "' + work.toLowerCase() + '" reads three times more expensive than "embroidery".',
        'Four or five sizes everywhere — custom XS–3XL is open ground.',
        'Flat-lay photography — your real-place hero + a detail shot changes the price band.'
      ],
      better: [
        'Custom-stitched to measurement, XS–3XL, no extra charge — answers "will it fit my waist and fall right?"',
        'Publish the spec sheet buyers want to compare (flare, weight, dupatta length).',
        'Lead the listing with the occasion the colour is for, not the fabric.',
        'Same-week dispatch against premium houses that ship weeks out.'
      ]
    };
  }

  /* Word-openable .doc (HTML with a Word namespace — opens cleanly in Word, Google Docs, Pages) */
  function toDoc(p) {
    var a = analysis(p);
    var body = '<h1>' + a.title + '</h1>' +
      '<p><b>SKU:</b> ' + p.sku + ' &nbsp; <b>Category:</b> ' + p.cat + ' &nbsp; <b>Colour:</b> ' + p.colour + ' &nbsp; <b>Fabric:</b> ' + p.fabric + '</p>' +
      '<h2>1 · The market</h2><p>' + a.market + '</p>' +
      '<h2>2 · Trends to ride</h2><ul>' + a.trends.map(function (t) { return '<li>' + t + '</li>'; }).join('') + '</ul>' +
      '<h2>3 · Competitor analysis</h2><table border="1" cellpadding="6" style="border-collapse:collapse"><tr style="background:#5B2D8E;color:#fff"><th>Tier</th><th>How they sell it</th><th>How you beat them</th></tr>' +
      a.competitors.map(function (c) { return '<tr><td><b>' + c.tier + '</b></td><td>' + c.how + '</td><td>' + c.beat + '</td></tr>'; }).join('') + '</table>' +
      '<h2>4 · Gap analysis — what nobody does</h2><ul>' + a.gaps.map(function (g) { return '<li>' + g + '</li>'; }).join('') + '</ul>' +
      '<h2>5 · What you can do better</h2><ul>' + a.better.map(function (b) { return '<li>' + b + '</li>'; }).join('') + '</ul>' +
      '<hr><p style="color:#6B5A86"><i>Vastrangam · Crafted in Surat · generated by Vastrangam AI Engine. For today\'s live competitor prices and URLs, ask for a fresh in-session research pass.</i></p>';
    return '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><style>body{font-family:Georgia,serif;color:#1A0B38;line-height:1.5}h1{color:#5B2D8E}h2{color:#5B2D8E;border-bottom:1px solid #ddd;padding-bottom:4px}</style></head><body>' + body + '</body></html>';
  }

  VA.action('dldoc', function (b) {
    var run = DB().runs.filter(function (r) { return r.id === b.getAttribute('data-id'); })[0]; if (!run) return;
    var html = toDoc(run.pack);
    var blob = new Blob(['﻿' + html], { type: 'application/msword' });
    var a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = run.pack.sku + '-market-analysis.doc'; a.click();
    VA.toast('Market analysis .doc downloaded');
  });
  /* upgrade the whole pack's prose with a connected model (optional) */
  VA.action('aiupgrade', function (b) {
    var run = DB().runs.filter(function (r) { return r.id === b.getAttribute('data-id'); })[0]; if (!run) return;
    if (!VAI.anyText()) { VA.toast('Connect a model on Connectors to upgrade the prose'); return; }
    var p = run.pack;
    VA.toast('Upgrading the opening with the connected model…');
    VAI.callText('Rewrite this Indian ethnic-wear product opening in 2 short paragraphs, humanized, NO product-noun opener, concrete Surat detail, for a ' + p.occ.replace('-', ' ') + '. Keep it under 90 words. Product: ' + p.colour + ' ' + p.fabric + ' ' + p.cat + ' with ' + p.work + '.', { max: 300, fallback: '' })
      .then(function (res) {
        if (res.text && res.text.length > 40) { p.aiOpening = res.text.trim(); VA.save(); VA.toast('Opening upgraded by ' + res.provider); VA.render(); }
        else VA.toast('Model returned nothing — keeping the built-in version');
      }).catch(function () { VA.toast('Upgrade failed — built-in version kept'); });
  });

  VA.ANALYSIS = { analysis: analysis, toDoc: toDoc };
})();
