/* ═══════════ Vastrangam AI Engine — Connectors, Wiring, Backup & Health, self-tests ═══════════ */
(function () {
  'use strict';
  var H = VA.H, esc = VA.esc, DB = function () { return VA.DB; };

  /* ── CONNECTORS ── every capability has alternatives + a built-in way that needs nobody ── */
  var CAPS = [
    { cap: 'AI text / chat', builtin: 'Built-in rules engine (offline)', alts: 'Claude · OpenAI · Gemini · Mistral · Groq · OpenRouter · Ollama · LM Studio' },
    { cap: 'Image generation', builtin: 'Design Studio canvas (offline)', alts: 'Krea · Midjourney · Stable Diffusion · Adobe Firefly' },
    { cap: 'Video render (MP4/H.264)', builtin: 'WebM · GIF · frames (offline)', alts: 'FFmpeg service · Remotion · Shotstack' },
    { cap: 'Voiceover', builtin: 'Script export (offline)', alts: 'ElevenLabs · Play.ht · Azure TTS · Coqui (local)' },
    { cap: 'Music', builtin: 'Suno lyric + tag export (offline)', alts: 'Suno · Udio · Mubert' },
    { cap: 'Spreadsheets', builtin: 'Built-in .xlsx/.csv engine (offline)', alts: 'Google Sheets · Excel · Airtable' },
    { cap: 'Automation', builtin: 'Webhook JSON export (offline)', alts: 'Make · n8n · Zapier · Pabbly' },
    { cap: 'Publishing', builtin: 'Payload preview + log (offline)', alts: 'Shopify · Amazon SP-API · Flipkart · Meta · Ajio' }
  ];
  VA.view('conn', function () {
    return H.head('Connectors', 'Connectors', 'Nothing here is locked to one company. Every capability has a built-in way that needs no internet and no account, and a list of services you can plug in when you want to.') +
      H.panel('Every capability, and its alternatives',
        H.table([
          { label: 'Capability', fmt: function (r) { return '<b>' + esc(r.cap) + '</b>'; } },
          { label: 'Built-in (offline)', fmt: function (r) { return H.tag(r.builtin, 'grn'); } },
          { label: 'Plug in instead', fmt: function (r) { return esc(r.alts); } }
        ], CAPS)) +
      H.panel('The AI assistant', '<p>The assistant is the built-in engine by default — it reads your records and works offline. Connect any model for free-form chat from the assistant\'s <b>change</b> link.</p>' +
        '<div class="btnrow" style="margin-top:10px"><button class="btn p" data-act="askprovset">Choose an AI model</button></div>') +
      H.note('This is the no-lock-in rule made real: the app works fully with none of these connected, and you can swap any one of them without touching the rest.');
  });

  /* ── WIRING ── */
  VA.view('wiring', function () {
    var rows = [
      ['Content runs count', 'runs table', 'length of DB.runs'],
      ['Avg QA score', 'each run\'s QA gate', 'mean of run.qa across runs'],
      ['Scheduled count', 'calendar table', 'entries where status = Scheduled'],
      ['Published count', 'publish log', 'entries where result = Published'],
      ['Channels connected', 'channels table', 'entries where connected = true'],
      ['Every title / bullet / listing', 'the vocab libraries + your input', 'generated by the 13-phase engine on read — never stored pre-baked'],
      ['9-sheet Excel', 'the current run\'s pack', 'built by the spreadsheet engine at download time']
    ];
    return H.head('Wiring', 'Where every figure comes from', 'This app owns one set of records. Every number on every screen is worked out from it when the screen opens — nothing is pre-calculated or left stale.') +
      H.note('One data core: Products · Content runs · Assets · Channels · Calendar · Publish log — every screen reads and writes these.') +
      H.panel('Every figure and its source', H.table([{ label: 'Figure', k: 'c0' }, { label: 'Comes from', k: 'c1' }, { label: 'How it is worked out', k: 'c2' }],
        rows.map(function (r) { return { c0: r[0], c1: r[1], c2: r[2] }; }))) +
      '<div class="two">' +
      H.panel('Why the five engines are one app', '<p>Generate a pack in Content Engine and it is instantly available to Video Studio, Design Studio and Publisher — because there is only one set of records underneath all five. Nothing is synced; there is nothing to sync.</p>') +
      H.panel('What runs offline', '<div class="cascade"><div class="cl"><span class="d">✓</span><div>The 13-phase generator</div></div><div class="cl"><span class="d">✓</span><div>The image canvas and adjustments</div></div><div class="cl"><span class="d">✓</span><div>The video timeline, WebM, GIF and frames</div></div><div class="cl"><span class="d">✓</span><div>The spreadsheet engine and the assistant</div></div></div>') +
      '</div>';
  });

  /* ── BACKUP & HEALTH ── */
  VA.view('backup', function () {
    var t = VA.runTests();
    var rows = t.log.map(function (l) { return '<div class="kv"><span>' + esc(l.name) + '</span><b>' + (l.ok ? H.tag('pass', 'grn') : H.tag('fail', 'red')) + '</b></div>'; }).join('');
    return H.head('System', 'Backup & Health', 'Your data lives in this browser, on this device. Export a backup any time — it is the one habit that matters.') +
      H.kpis([
        { l: 'Self-tests', v: t.pass + '/' + (t.pass + t.fail), d: t.fail ? t.fail + ' failing' : 'all pass', cls: t.fail ? 'r' : 'g', icon: 'check', tone: t.fail ? 'red' : 'green' },
        { l: 'Storage', v: sizeKB() + ' KB', d: 'in this browser', icon: 'save', tone: 'blue' },
        { l: 'Runs held', v: DB().runs.length, d: 'content packs', icon: 'pen', tone: 'violet' }
      ]) +
      H.panel('Your data', '<div class="btnrow"><button class="btn p" data-act="expjson">Export JSON backup</button><button class="btn" data-act="impjson">Import a backup</button><button class="btn" data-act="reseed">Reload demo data</button><button class="btn d" data-act="wipe">Wipe all</button></div>' +
        '<input type="file" id="impfile" accept=".json" style="display:none">' +
        '<p class="hint" style="margin-top:9px">The data sits in a private store labelled <code>vastrangam_ai_engine_v1</code>. It survives closing the app; it does not travel between devices by itself — use the backup file.</p>') +
      H.panel('Self-tests <span class="badge">' + t.pass + '/' + (t.pass + t.fail) + '</span>',
        '<p class="hint" style="margin-bottom:10px">Every time the app opens it checks its own arithmetic. Each line is in plain language — you can read what was checked.</p>' + rows);
  });
  function sizeKB() { try { return Math.round(JSON.stringify(DB()).length / 1024); } catch (e) { return 0; } }
  VA.action('expjson', function () { var blob = new Blob([JSON.stringify(DB(), null, 2)], { type: 'application/json' }); var a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'vastrangam-ai-engine-backup.json'; a.click(); VA.toast('Backup exported'); });
  VA.action('impjson', function () { VA.$('impfile').click(); });
  VA.action('reseed', function () { if (confirm('Reload demo data? This replaces current data.')) { VA.DB = LIB.seed(); VA.DB.__v = 1; VA.save(); VA.toast('Demo reloaded'); VA.go('home'); } });
  VA.action('wipe', function () { if (confirm('Wipe ALL data? Take a backup first — this cannot be undone.')) { VA.DB = LIB.seed(); VA.DB.__v = 1; VA.DB.runs = []; VA.DB.calendar = []; VA.DB.publog = []; VA.save(); VA.toast('Wiped'); VA.go('home'); } });
  VA.view('backup').after = function () { var f = VA.$('impfile'); if (f) f.onchange = function () { var file = f.files[0]; if (!file) return; var rd = new FileReader(); rd.onload = function (e) { try { VA.DB = JSON.parse(e.target.result); VA.save(); VA.toast('Imported'); VA.go('home'); } catch (x) { VA.toast('Bad file'); } }; rd.readAsText(file); }; };

  /* ── SELF-TESTS ── */
  VA.test(function (t, DB) {
    t('the seed has products, runs and channels', DB.products.length > 0 && DB.runs.length > 0 && DB.channels.length > 0);
    t('every seeded run carries a full pack', DB.runs.every(function (r) { return r.pack && r.pack.title; }));
    t('every generated pack scores its own QA gate', DB.runs.every(function (r) { return r.pack.qa && r.pack.qa.total === r.pack.qa.checks.length; }));
  });
  VA.test(function (t, DB) {
    /* the generator, exercised live */
    var p = VA.CE.generate({ desc: 'mehendi green roman silk zari anarkali', occ: 'mehendi', price: 2499 });
    t('the generator detects the category from words', p.cat === 'Anarkali Suit');
    t('it maps to a premium colour name, never a basic one', p.colour.indexOf('Green') >= 0);
    t('the Shopify body carries the AEO question block', p.bodyHTML.indexOf('(What is this product?)') >= 0);
    t('four distinct title variants are produced', new Set(Object.values(p.titles)).size === 4);
    t('the SEO title stays within 60 characters', p.meta.title.length <= 60);
    t('the handle is hyphenated and within 60 chars', /^[a-z0-9-]+$/.test(p.handle) && p.handle.length <= 60);
    t('the Suno lyrics contain no product word', !LIB.PRODUCT_NOUNS.some(function (n) { return p.suno.toLowerCase().indexOf(n) >= 0; }));
    t('the opening line does not start with the product noun', p.qa.checks.filter(function (c) { return /Opening line/.test(c.name); })[0].ok);
    t('the 9-sheet export builds nine sheets', VA.buildSheets(p).length === 9);
    t('the first sheet is the Shopify master with 23 columns', VA.buildSheets(p)[0].rows[0].length === 23);
    t('all five marketplaces get copy', !!(p.marketplace.amazon && p.marketplace.flipkart && p.marketplace.myntra && p.marketplace.ajio && p.marketplace.meesho));
    t('the QA gate runs ten checks', p.qa.total === 10);
  });
  VA.test(function (t, DB) {
    /* the assistant reads live records */
    var r = VA.ASK.respond('how many products do i have');
    t('the assistant answers product count from live data', r.text.indexOf(String(DB.products.length)) >= 0);
    t('the assistant defines a fabric term', VA.ASK.respond('what is roman silk').text.indexOf('Roman Silk') >= 0);
    t('the assistant states the password policy', /never asks/.test(VA.ASK.respond('do you need my password').text));
  });
})();
